export const CROPS = [
  {
    "id": "wheat",
    "name": "Wheat",
    "tool": "Euclid's Wheat Sickle",
    "color": "gold",
    "icon": "W",
    "toolMatch": "euclid s wheat",
    "toolVerified": "2026-09-16",
    "toolSource": "https://hypixelskyblock.minecraft.wiki/w/Farming_Tools"
  },
  {
    "id": "carrot",
    "name": "Carrot",
    "tool": "Gauss Carrot Shovel",
    "color": "orange",
    "icon": "C",
    "toolMatch": "gauss carrot",
    "toolVerified": "2026-09-16",
    "toolSource": "https://hypixelskyblock.minecraft.wiki/w/Farming_Tools"
  },
  {
    "id": "potato",
    "name": "Potato",
    "tool": "Pythagorean Potato Shovel",
    "color": "amber",
    "icon": "P",
    "toolMatch": "pythagorean potato",
    "toolVerified": "2026-09-16",
    "toolSource": "https://hypixelskyblock.minecraft.wiki/w/Farming_Tools"
  },
  {
    "id": "pumpkin",
    "name": "Pumpkin",
    "tool": "Pumpkin Dicer",
    "color": "orange",
    "icon": "Pu",
    "toolMatch": "pumpkin",
    "toolVerified": "2026-09-16",
    "toolSource": "https://hypixelskyblock.minecraft.wiki/w/Farming_Tools"
  },
  {
    "id": "melon",
    "name": "Melon",
    "tool": "Melon Dicer",
    "color": "green",
    "icon": "M",
    "toolMatch": "melon",
    "toolVerified": "2026-09-16",
    "toolSource": "https://hypixelskyblock.minecraft.wiki/w/Farming_Tools"
  },
  {
    "id": "mushroom",
    "name": "Mushroom",
    "tool": "Fungi Cutter",
    "color": "red",
    "icon": "Mu",
    "toolMatch": "fungi",
    "toolVerified": "2026-09-16",
    "toolSource": "https://hypixelskyblock.minecraft.wiki/w/Farming_Tools"
  },
  {
    "id": "cactus",
    "name": "Cactus",
    "tool": "Cactus Knife",
    "color": "emerald",
    "icon": "Ca",
    "toolMatch": "cactus",
    "toolVerified": "2026-09-16",
    "toolSource": "https://hypixelskyblock.minecraft.wiki/w/Farming_Tools"
  },
  {
    "id": "sugar-cane",
    "name": "Sugar Cane",
    "tool": "Turing Sugar Cane Cutter",
    "color": "lime",
    "icon": "S",
    "toolMatch": "turing sugar cane",
    "toolVerified": "2026-09-16",
    "toolSource": "https://hypixelskyblock.minecraft.wiki/w/Farming_Tools"
  },
  {
    "id": "cocoa-beans",
    "name": "Cocoa Beans",
    "tool": "Cocoa Chopper",
    "color": "brown",
    "icon": "Co",
    "toolMatch": "cocoa",
    "toolVerified": "2026-09-16",
    "toolSource": "https://hypixelskyblock.minecraft.wiki/w/Farming_Tools"
  },
  {
    "id": "nether-wart",
    "name": "Nether Wart",
    "tool": "Newton Nether Wart Cutter",
    "color": "crimson",
    "icon": "N",
    "toolMatch": "newton nether wart",
    "toolVerified": "2026-09-16",
    "toolSource": "https://hypixelskyblock.minecraft.wiki/w/Farming_Tools"
  },
  {
    "id": "sunflower",
    "name": "Sunflower",
    "tool": "Eclipse Sickle",
    "color": "gold",
    "icon": "Su",
    "toolMatch": "eclipse",
    "toolVerified": "2026-09-16",
    "toolSource": "https://hypixelskyblock.minecraft.wiki/w/Farming_Tools"
  },
  {
    "id": "moonflower",
    "name": "Moonflower",
    "tool": "Eclipse Sickle",
    "color": "violet",
    "icon": "Mo",
    "toolMatch": "eclipse",
    "toolVerified": "2026-09-16",
    "toolSource": "https://hypixelskyblock.minecraft.wiki/w/Farming_Tools"
  },
  {
    "id": "wild-rose",
    "name": "Wild Rose",
    "tool": "Wild Rose Cutter",
    "color": "rose",
    "icon": "WR",
    "toolMatch": "wild rose",
    "toolVerified": "2026-09-16",
    "toolSource": "https://hypixelskyblock.minecraft.wiki/w/Farming_Tools"
  }
];

export const UPGRADES = [
  {
    "id": "account-skill-farming-skill-level",
    "category": "Account/Skill",
    "section": "account",
    "name": "Farming Skill level",
    "metric": "Crop Yield",
    "modeScope": "Any",
    "cropScope": "Any",
    "status": "ACTIVE",
    "max": 60,
    "stepGain": 4,
    "manualDefault": null,
    "rawMarginal": 4,
    "hypercharge": false,
    "notes": "+4 Farming Fortune per level, up to +240.",
    "source": "https://wiki.eliteskyblock.com/Farming_Fortune",
    "workbookRank": 29
  },
  {
    "id": "anita-extra-farming-fortune-perk",
    "category": "Anita",
    "section": "account",
    "name": "Extra Farming Fortune perk",
    "metric": "Crop Yield",
    "modeScope": "Any",
    "cropScope": "Any",
    "status": "ACTIVE",
    "max": 15,
    "stepGain": 4,
    "manualDefault": null,
    "rawMarginal": 4,
    "hypercharge": false,
    "notes": "+4 FF per tier, up to +60.",
    "source": "https://wiki.eliteskyblock.com/Farming_Fortune",
    "workbookRank": 30
  },
  {
    "id": "garden-garden-plots-unlocked",
    "category": "Garden",
    "section": "account",
    "name": "Garden plots unlocked",
    "metric": "Crop Yield",
    "modeScope": "Any",
    "cropScope": "Any",
    "status": "ACTIVE",
    "max": 24,
    "stepGain": 3,
    "manualDefault": null,
    "rawMarginal": 3,
    "hypercharge": false,
    "notes": "+3 FF per owned plot; all 24 = +72.",
    "source": "https://wiki.eliteskyblock.com/Farming_Fortune",
    "workbookRank": 32
  },
  {
    "id": "account-upgrade-elizabeth-garden-farming-fortune",
    "category": "Account Upgrade",
    "section": "account",
    "name": "Elizabeth Garden Farming Fortune",
    "metric": "Crop Yield",
    "modeScope": "Any",
    "cropScope": "Any",
    "status": "ACTIVE",
    "max": 10,
    "stepGain": 4,
    "manualDefault": null,
    "rawMarginal": 4,
    "hypercharge": false,
    "notes": "+4 FF per level, max +40; time-gated.",
    "source": "https://wiki.eliteskyblock.com/Farming_Fortune",
    "workbookRank": 31
  },
  {
    "id": "garden-pest-garden-bestiary-ff",
    "category": "Garden",
    "section": "account",
    "name": "Pest/Garden Bestiary FF",
    "metric": "Crop Yield",
    "modeScope": "Any",
    "cropScope": "Any",
    "status": "VERIFY",
    "max": 1,
    "stepGain": 0,
    "manualDefault": null,
    "rawMarginal": 0,
    "hypercharge": false,
    "notes": "Dynamic. Current community references disagree after later pest additions; enter the next marginal FF manually from the in-game tooltip.",
    "source": "https://hypixel-skyblock.fandom.com/wiki/Farming_Fortune",
    "workbookRank": null
  },
  {
    "id": "greenhouse-mutation-analysis-rewards",
    "category": "Greenhouse",
    "section": "account",
    "name": "Mutation Analysis rewards",
    "metric": "Crop Yield",
    "modeScope": "Any",
    "cropScope": "Any",
    "status": "VERIFY",
    "max": 1,
    "stepGain": 0,
    "manualDefault": null,
    "rawMarginal": 0,
    "hypercharge": false,
    "notes": "Reported up to +30 FF; verify current analyzer reward state.",
    "source": "https://hypixel-skyblock.fandom.com/wiki/Farming_Fortune",
    "workbookRank": null
  },
  {
    "id": "consumable-rosewater-flask-permanent-stacks",
    "category": "Consumable",
    "section": "account",
    "name": "Rosewater Flask permanent stacks",
    "metric": "Crop Yield",
    "modeScope": "Any",
    "cropScope": "Any",
    "status": "VERIFY",
    "max": 5,
    "stepGain": 1,
    "manualDefault": null,
    "rawMarginal": 1,
    "hypercharge": false,
    "notes": "Reported +1 FF per permanent use, up to 5.",
    "source": "https://hypixel-skyblock.fandom.com/wiki/Farming_Fortune",
    "workbookRank": 35
  },
  {
    "id": "accessory-relic-of-power-perfect-peridot-effect",
    "physicalItemId": "POWER_RELIC",
    "category": "Accessory",
    "section": "accessories",
    "name": "Relic of Power + Perfect Peridot effect",
    "metric": "Crop Yield",
    "modeScope": "Any",
    "cropScope": "Any",
    "status": "ACTIVE",
    "max": 1,
    "stepGain": 5,
    "manualDefault": null,
    "rawMarginal": 5,
    "hypercharge": false,
    "notes": "Perfect Peridot contributes half value in Relic of Power; commonly +5 FF.",
    "source": "https://wiki.eliteskyblock.com/Farming_Fortune",
    "workbookRank": 24
  },
  {
    "id": "accessory-fermento-artifact",
    "physicalItemId": "FERMENTO_ARTIFACT",
    "category": "Accessory",
    "section": "accessories",
    "name": "Fermento Artifact",
    "metric": "Crop Yield",
    "modeScope": "Any",
    "cropScope": "Any",
    "status": "ACTIVE",
    "max": 1,
    "stepGain": 30,
    "manualDefault": null,
    "rawMarginal": 30,
    "hypercharge": false,
    "notes": "Cropie → Squash → Fermento → Helianthus progression. Helianthus replaces this bonus when upgraded; do not stack tiers.",
    "source": "https://wiki.eliteskyblock.com/Farming_Fortune",
    "workbookRank": 14
  },
  {
    "id": "accessory-helianthus-relic",
    "physicalItemId": "HELIANTHUS_RELIC",
    "category": "Accessory",
    "section": "accessories",
    "name": "Helianthus Relic",
    "metric": "Crop Yield",
    "modeScope": "Any",
    "cropScope": "Any",
    "status": "ACTIVE",
    "max": 1,
    "stepGain": 40,
    "manualDefault": null,
    "rawMarginal": 40,
    "hypercharge": false,
    "notes": "Final tier of the Cropie → Squash → Fermento → Helianthus accessory progression; +40 FF while breaking crops.",
    "source": "https://hypixel-skyblock.fandom.com/wiki/Farming_Fortune",
    "workbookRank": 13
  },
  {
    "id": "crop-progression-crop-upgrade-selected-crop",
    "category": "Crop Progression",
    "section": "crops",
    "name": "Crop Upgrade (selected crop)",
    "metric": "Crop Yield",
    "modeScope": "Any",
    "cropScope": "Any",
    "status": "ACTIVE",
    "max": 9,
    "stepGain": 5,
    "manualDefault": null,
    "rawMarginal": 5,
    "hypercharge": false,
    "notes": "+5 Crop Fortune per level, max +45 for the selected crop.",
    "source": "https://wiki.eliteskyblock.com/Farming_Fortune",
    "workbookRank": 25
  },
  {
    "id": "jacob-personal-best-perk-selected-crop",
    "category": "Jacob",
    "section": "crops",
    "name": "Personal Best perk (selected crop)",
    "metric": "Crop Yield",
    "modeScope": "Any",
    "cropScope": "Any",
    "status": "ACTIVE",
    "max": 1,
    "stepGain": 0,
    "manualDefault": null,
    "rawMarginal": 0,
    "hypercharge": false,
    "notes": "Nonlinear/current-PB dependent; enter marginal Crop Fortune manually. Max reference +100.",
    "source": "https://wiki.eliteskyblock.com/Farming_Fortune",
    "workbookRank": null
  },
  {
    "id": "tool-tool-base-counter-fortune",
    "category": "Tool Level",
    "section": "tools",
    "name": "Farming Tool level",
    "metric": "Crop Yield",
    "modeScope": "Any",
    "cropScope": "Any",
    "status": "ACTIVE",
    "max": 50,
    "stepGain": 4,
    "manualDefault": null,
    "rawMarginal": 4,
    "hypercharge": false,
    "notes": "Current Greenhouse tool system: each tool level grants +4 Fortune for its crop(s), up to +200 at level 50. Mk. II/Mk. III and Overclocker 3000 gate later levels; levels 41-50 each require an Overclocker 3000.",
    "source": "https://hypixel-skyblock.fandom.com/wiki/Eclipse_Hoe",
    "workbookRank": 12
  },
  {
    "id": "tool-mk-ii",
    "category": "Tool Tier",
    "section": "tools",
    "name": "Tool Mk. II",
    "metric": "Progress Gate",
    "modeScope": "Any",
    "cropScope": "Any",
    "status": "ACTIVE",
    "max": 1,
    "stepGain": 0,
    "manualDefault": null,
    "rawMarginal": 0,
    "hypercharge": false,
    "notes": "Raises the tool tier/rarity and is required for later tool levels. It also changes reforge and gemstone scaling, so its exact marginal Fortune is setup-dependent.",
    "source": "https://hypixel-skyblock.fandom.com/wiki/Eclipse_Hoe",
    "workbookRank": null
  },
  {
    "id": "tool-mk-iii",
    "category": "Tool Tier",
    "section": "tools",
    "name": "Tool Mk. III",
    "metric": "Progress Gate",
    "modeScope": "Any",
    "cropScope": "Any",
    "status": "ACTIVE",
    "max": 1,
    "stepGain": 0,
    "manualDefault": null,
    "rawMarginal": 0,
    "hypercharge": false,
    "notes": "Final crafted tier for specialized farming tools. Required for the high-level portion of the level path; rarity also affects reforges and gemstone value.",
    "source": "https://hypixel-skyblock.fandom.com/wiki/Eclipse_Hoe",
    "workbookRank": null
  },
  {
    "id": "tool-overclocker-3000",
    "category": "Tool Level Gate",
    "section": "tools",
    "name": "Overclocker 3000",
    "metric": "Progress Gate",
    "modeScope": "Any",
    "cropScope": "Any",
    "status": "ACTIVE",
    "max": 10,
    "stepGain": 0,
    "manualDefault": null,
    "rawMarginal": 0,
    "hypercharge": false,
    "notes": "One is required for each Farming Tool level from 41 through 50. Ten are required to unlock level 50; the Fortune itself is counted by Farming Tool level to avoid double counting.",
    "source": "https://hypixel-skyblock.fandom.com/wiki/Eclipse_Hoe",
    "workbookRank": null
  },
  {
    "id": "tool-enchant-dedication",
    "category": "Tool Enchant",
    "section": "tools",
    "name": "Dedication",
    "metric": "Crop Yield",
    "modeScope": "Any",
    "cropScope": "Any",
    "status": "ACTIVE",
    "max": 4,
    "stepGain": 0,
    "manualDefault": null,
    "rawMarginal": 0,
    "hypercharge": false,
    "notes": "Scales with Garden milestone/selected crop. Max reference +92 Crop Fortune; enter the next marginal delta manually.",
    "source": "https://wiki.eliteskyblock.com/Farming_Fortune",
    "workbookRank": null
  },
  {
    "id": "tool-enchant-turbo-crop",
    "category": "Tool Enchant",
    "section": "tools",
    "name": "Turbo-Crop",
    "metric": "Crop Yield",
    "modeScope": "Any",
    "cropScope": "Any",
    "status": "ACTIVE",
    "max": 7,
    "stepGain": 5,
    "manualDefault": null,
    "rawMarginal": 5,
    "hypercharge": false,
    "notes": "+5 Crop Fortune per level for its crop, maxing at +35 Crop Fortune at Turbo-Crop VII. VI comes from a Turbo Gourd and VII from an Enchanted Turbo Gourd; I-V are contests/Librarian and book combining.",
    "source": "https://hypixelskyblock.minecraft.wiki/w/Farming_Fortune",
    "lastVerified": "2026-09-16",
    "workbookRank": 26
  },
  {
    "id": "jacob-accessory-anita-accessory-crop-bonus",
    "physicalItemId": "ANITA_ARTIFACT",
    "category": "Accessory",
    "section": "accessories",
    "name": "Anita accessory crop bonus",
    "metric": "Crop Yield",
    "modeScope": "Jacob Contest",
    "cropScope": "Any",
    "status": "ACTIVE",
    "max": 1,
    "stepGain": 25,
    "manualDefault": null,
    "rawMarginal": 25,
    "hypercharge": false,
    "notes": "Up to +25 crop-specific fortune when its boosted contest condition is met.",
    "source": "https://wiki.eliteskyblock.com/Farming_Fortune",
    "workbookRank": null
  },
  {
    "id": "permanent-crop-item-exportable-item-selected-crop",
    "category": "Permanent Crop Item",
    "section": "crops",
    "name": "Exportable item (selected crop)",
    "metric": "Crop Yield",
    "modeScope": "Any",
    "cropScope": "Any",
    "status": "VERIFY",
    "max": 1,
    "stepGain": 12,
    "manualDefault": null,
    "rawMarginal": 12,
    "hypercharge": false,
    "notes": "+12 selected-crop Fortune where an exportable item exists; availability differs by crop.",
    "source": "https://wiki.eliteskyblock.com/Farming_Fortune",
    "workbookRank": 22
  },
  {
    "id": "chocolate-factory-chocolate-factory-cocoa-perk",
    "category": "Chocolate Factory",
    "section": "account",
    "name": "Chocolate Factory Cocoa perk",
    "metric": "Crop Yield",
    "modeScope": "Any",
    "cropScope": "Cocoa Beans",
    "status": "ACTIVE",
    "max": 1,
    "stepGain": 25,
    "manualDefault": null,
    "rawMarginal": 25,
    "hypercharge": false,
    "notes": "+25 Cocoa Beans Fortune.",
    "source": "https://wiki.eliteskyblock.com/Farming_Fortune",
    "workbookRank": null
  },
  {
    "id": "chocolate-factory-refined-dark-cacao-permanent-bonus",
    "category": "Chocolate Factory",
    "section": "account",
    "name": "Refined Dark Cacao permanent bonus",
    "metric": "Crop Yield",
    "modeScope": "Any",
    "cropScope": "Cocoa Beans",
    "status": "ACTIVE",
    "max": 5,
    "stepGain": 1,
    "manualDefault": null,
    "rawMarginal": 1,
    "hypercharge": false,
    "notes": "0.27 changed this line from Global Fortune to Cocoa Fortune.",
    "source": "https://hypixel.net/threads/hypixel-skyblock-0-27-torrhus-canyon-critter-safari.6132090/",
    "workbookRank": null
  },
  {
    "id": "tool-enchant-cultivating-x",
    "category": "Tool Enchant",
    "section": "tools",
    "name": "Cultivating X",
    "metric": "Crop Yield",
    "modeScope": "Any",
    "cropScope": "Any",
    "status": "ACTIVE",
    "max": 10,
    "stepGain": 2,
    "manualDefault": null,
    "rawMarginal": 2,
    "hypercharge": false,
    "notes": "+2 FF per Cultivating tier; max +20 at Cultivating X.",
    "source": "https://hypixelskyblock.minecraft.wiki/w/Cultivating",
    "workbookRank": 34
  },
  {
    "id": "tool-enchant-harvesting-vi",
    "category": "Tool Enchant",
    "section": "tools",
    "name": "Harvesting VI",
    "metric": "Crop Yield",
    "modeScope": "Any",
    "cropScope": "Any",
    "status": "ACTIVE",
    "max": 6,
    "stepGain": 12.5,
    "manualDefault": null,
    "rawMarginal": 12.5,
    "hypercharge": false,
    "notes": "0.27 restored Harvesting VI to +75 total. Axes now use Harvesting too; Sunder was removed.",
    "source": "https://hypixel.net/threads/aug-3-0-27-alpha-changes-2.6134812/",
    "workbookRank": 21
  },
  {
    "id": "tool-farming-for-dummies",
    "category": "Tool",
    "section": "tools",
    "name": "Farming for Dummies",
    "metric": "Crop Yield",
    "modeScope": "Any",
    "cropScope": "Any",
    "status": "ACTIVE",
    "max": 5,
    "stepGain": 1,
    "manualDefault": null,
    "rawMarginal": 1,
    "hypercharge": false,
    "notes": "+1 FF per book, up to 5.",
    "source": "https://wiki.eliteskyblock.com/Farming_Fortune",
    "workbookRank": 36
  },
  {
    "id": "tool-reforge-blessed-reforge",
    "category": "Tool Reforge",
    "section": "tools",
    "name": "Blessed reforge",
    "metric": "Crop Yield",
    "modeScope": "Any",
    "cropScope": "Any",
    "status": "ACTIVE",
    "max": 1,
    "stepGain": 20,
    "manualDefault": null,
    "rawMarginal": 20,
    "hypercharge": false,
    "notes": "Max-rarity reference +20 FF; compare to Bountiful if optimizing coins rather than collection.",
    "source": "https://wiki.eliteskyblock.com/Farming_Fortune",
    "workbookRank": 18
  },
  {
    "id": "tool-reforge-bountiful-reforge",
    "category": "Tool Reforge",
    "section": "tools",
    "name": "Bountiful reforge",
    "metric": "Crop Yield",
    "modeScope": "Any",
    "cropScope": "Any",
    "status": "ACTIVE",
    "max": 1,
    "stepGain": 10,
    "manualDefault": null,
    "rawMarginal": 10,
    "hypercharge": false,
    "notes": "Max-rarity reference +10 FF; can win for coins despite lower Fortune.",
    "source": "https://wiki.eliteskyblock.com/Farming_Fortune",
    "workbookRank": 23
  },
  {
    "id": "tool-gem-perfect-peridot-on-farming-tool",
    "category": "Tool Gem",
    "section": "tools",
    "name": "Perfect Peridot on Farming Tool",
    "metric": "Crop Yield",
    "modeScope": "Any",
    "cropScope": "Any",
    "status": "ACTIVE",
    "max": 1,
    "stepGain": 30,
    "manualDefault": null,
    "rawMarginal": 30,
    "hypercharge": false,
    "notes": "Tool slot total depends on tool/rarity; reference +20/+30. Override manually if your tool has a different total.",
    "source": "https://wiki.eliteskyblock.com/Farming_Fortune",
    "workbookRank": 15
  },
  {
    "id": "tool-recombobulator-effect-on-tool-stats",
    "category": "Tool",
    "section": "tools",
    "name": "Recombobulator effect on tool stats",
    "metric": "Crop Yield",
    "modeScope": "Any",
    "cropScope": "Any",
    "status": "VERIFY",
    "max": 1,
    "stepGain": 0,
    "manualDefault": null,
    "rawMarginal": 0,
    "hypercharge": false,
    "notes": "Indirect through reforge/gem rarity scaling. Enter actual tooltip delta manually.",
    "source": "https://wiki.eliteskyblock.com/Farming_Fortune",
    "workbookRank": null
  },
  {
    "id": "garden-chip-cropshot-chip",
    "packAsset": "cropshot_chip",
    "category": "Garden Chip",
    "section": "chips",
    "name": "Cropshot Chip",
    "metric": "Crop Yield",
    "modeScope": "Any",
    "cropScope": "Any",
    "status": "ACTIVE",
    "max": 20,
    "stepGain": 5,
    "manualDefault": null,
    "rawMarginal": 5,
    "hypercharge": false,
    "notes": "At Legendary: +5 FF per chip level, max +100. Adjust manual delta if current rarity uses +3/+4 per level.",
    "source": "https://hypixel.net/threads/aug-3-0-27-alpha-changes-2.6134812/",
    "workbookRank": 27
  },
  {
    "id": "garden-chip-hypercharge-chip-next-level",
    "packAsset": "hypercharge_chip",
    "category": "Garden Chip",
    "section": "chips",
    "name": "Hypercharge Chip next level",
    "metric": "Crop Yield",
    "modeScope": "Any",
    "cropScope": "Any",
    "status": "ACTIVE",
    "max": 20,
    "stepGain": 0,
    "manualDefault": 0.25,
    "rawMarginal": 0.25,
    "hypercharge": false,
    "notes": "Special formula: marginal value equals active eligible temporary base FF × next chip percentage step.",
    "source": "https://hypixel.net/threads/april-21-fossil-essence-shop-farming-toolkit-harvest-feast-changes.6083245/",
    "workbookRank": 38
  },
  {
    "id": "armor-helianthus-armor-base-stats",
    "category": "Armor",
    "section": "gear",
    "name": "Helianthus armor base stats",
    "metric": "Crop Yield",
    "modeScope": "Any",
    "cropScope": "Any",
    "status": "ACTIVE",
    "max": 1,
    "stepGain": 150,
    "manualDefault": null,
    "rawMarginal": 150,
    "hypercharge": false,
    "notes": "Full set base stats total +150 FF.",
    "source": "https://hypixel-skyblock.fandom.com/wiki/Helianthus_Armor",
    "workbookRank": 3
  },
  {
    "id": "armor-helianthus-feast-set-bonus",
    "category": "Armor",
    "section": "gear",
    "name": "Helianthus Feast set bonus",
    "metric": "Crop Yield",
    "modeScope": "Any",
    "cropScope": "Any",
    "status": "ACTIVE",
    "max": 1,
    "stepGain": 75,
    "manualDefault": null,
    "rawMarginal": 75,
    "hypercharge": false,
    "notes": "Four pieces grant +75 FF in addition to base piece stats.",
    "source": "https://hypixel-skyblock.fandom.com/wiki/Helianthus_Armor",
    "workbookRank": 7
  },
  {
    "id": "armor-reforge-mossy-on-full-armor",
    "category": "Armor Reforge",
    "section": "gear",
    "name": "Mossy on full armor",
    "metric": "Crop Yield",
    "modeScope": "Any",
    "cropScope": "Any",
    "status": "ACTIVE",
    "max": 1,
    "stepGain": 120,
    "manualDefault": null,
    "rawMarginal": 120,
    "hypercharge": false,
    "notes": "Full max-rarity set reference +120 FF.",
    "source": "https://wiki.eliteskyblock.com/Farming_Fortune",
    "workbookRank": 4
  },
  {
    "id": "armor-gem-perfect-peridot-on-full-armor",
    "category": "Armor Gem",
    "section": "gear",
    "name": "Perfect Peridot on full armor",
    "metric": "Crop Yield",
    "modeScope": "Any",
    "cropScope": "Any",
    "status": "ACTIVE",
    "max": 1,
    "stepGain": 80,
    "manualDefault": null,
    "rawMarginal": 80,
    "hypercharge": false,
    "notes": "Four armor slots reference +80 FF total.",
    "source": "https://wiki.eliteskyblock.com/Farming_Fortune",
    "workbookRank": 6
  },
  {
    "id": "armor-enchant-pesterminator-vi-on-full-armor",
    "category": "Armor Enchant",
    "section": "gear",
    "name": "Pesterminator VI on full armor",
    "metric": "Crop Yield",
    "modeScope": "Any",
    "cropScope": "Any",
    "status": "ACTIVE",
    "max": 1,
    "stepGain": 48,
    "manualDefault": null,
    "rawMarginal": 48,
    "hypercharge": false,
    "notes": "Reference +48 FF across four pieces; Bonus Pest Chance can be separately disabled with Pesthunter accessory line.",
    "source": "https://wiki.eliteskyblock.com/Farming_Fortune",
    "workbookRank": 11
  },
  {
    "id": "equipment-blossom-set-visitor-bonus",
    "category": "Equipment",
    "section": "gear",
    "name": "Blossom set visitor bonus",
    "metric": "Crop Yield",
    "modeScope": "Any",
    "cropScope": "Any",
    "status": "ACTIVE",
    "max": 1,
    "stepGain": 90,
    "manualDefault": null,
    "rawMarginal": 90,
    "hypercharge": false,
    "notes": "At 2,500 visitors, four Blossom pieces total +90 FF.",
    "source": "https://hypixel-skyblock.fandom.com/wiki/Blossom_Set",
    "workbookRank": 5
  },
  {
    "id": "equipment-reforge-rooted-on-full-equipment",
    "category": "Equipment Reforge",
    "section": "gear",
    "name": "Rooted on full equipment",
    "metric": "Crop Yield",
    "modeScope": "Any",
    "cropScope": "Any",
    "status": "VERIFY",
    "max": 1,
    "stepGain": 72,
    "manualDefault": null,
    "rawMarginal": 72,
    "hypercharge": false,
    "notes": "Current theoretical-max references use +72 FF on full recombobulated Blossom equipment.",
    "source": "https://hypixel-skyblock.fandom.com/wiki/Farming_Fortune",
    "workbookRank": 8
  },
  {
    "id": "equipment-enchant-green-thumb-v-on-equipment",
    "category": "Equipment Enchant",
    "section": "gear",
    "name": "Green Thumb V on equipment",
    "metric": "Crop Yield",
    "modeScope": "Any",
    "cropScope": "Any",
    "status": "VERIFY",
    "max": 1,
    "stepGain": 0,
    "manualDefault": null,
    "rawMarginal": 0,
    "hypercharge": false,
    "notes": "Scales with unique visitors served and piece count. Enter current next marginal delta from tooltips.",
    "source": "https://wiki.eliteskyblock.com/Farming_Fortune",
    "workbookRank": null
  },
  {
    "id": "equipment-zorro-s-cape-contest-swap",
    "category": "Equipment",
    "section": "gear",
    "name": "Zorro's Cape contest swap",
    "metric": "Crop Yield",
    "modeScope": "Jacob Contest",
    "cropScope": "Any",
    "status": "VERIFY",
    "max": 1,
    "stepGain": 0,
    "manualDefault": null,
    "rawMarginal": 0,
    "hypercharge": false,
    "notes": "Contest doubles cape stats; swap value depends on what equipment piece it replaces and its enchants/reforge.",
    "source": "https://wiki.eliteskyblock.com/Farming_Fortune",
    "workbookRank": null
  },
  {
    "id": "pet-item-green-bandana",
    "category": "Pet Item",
    "section": "pets",
    "name": "Green Bandana",
    "metric": "Crop Yield",
    "modeScope": "Any",
    "cropScope": "Any",
    "status": "ACTIVE",
    "max": 1,
    "stepGain": 60,
    "manualDefault": null,
    "rawMarginal": 60,
    "hypercharge": false,
    "notes": "+4 FF per Garden level, up to +60 at Garden 15. Pet-item replacement, not stackable with another pet item.",
    "source": "https://wiki.eliteskyblock.com/Farming_Fortune",
    "workbookRank": 9
  },
  {
    "id": "pet-switch-to-best-farming-pet",
    "category": "Pet",
    "section": "pets",
    "name": "Switch to best farming pet",
    "metric": "Crop Yield",
    "modeScope": "Any",
    "cropScope": "Any",
    "status": "ACTIVE",
    "max": 1,
    "stepGain": 0,
    "manualDefault": 280,
    "rawMarginal": 280,
    "hypercharge": false,
    "notes": "Linked to Pet_Calculator: compare candidate pet contribution against your currently equipped pet instead of adding both.",
    "source": "https://hypixel.net/threads/hypixel-skyblock-0-26-1-new-player-improvements-harvest-feast-changes-healing-revamp-and-more.6127383/",
    "workbookRank": 1
  },
  {
    "id": "attribute-shard-firefly-or-lunar-moth-shard",
    "attribute": "Solar Power, Lunar Power",
    "category": "Attribute Shard",
    "section": "shards",
    "name": "Firefly or Lunar Moth shard",
    "metric": "Crop Yield",
    "modeScope": "Any",
    "cropScope": "Any",
    "status": "ACTIVE",
    "max": 10,
    "stepGain": 5,
    "manualDefault": null,
    "rawMarginal": 5,
    "hypercharge": false,
    "notes": "+5 FF per level, max +50, conditional on day/night. Garden time setting can keep one active.",
    "source": "https://eliteskyblock.com/articles/news-foraging-and-hunting-update",
    "lastVerified": "2026-09-16",
    "workbookRank": 28
  },
  {
    "id": "attribute-shard-galaxy-fish-shard",
    "attribute": "Ultimate DNA",
    "category": "Attribute Shard",
    "section": "shards",
    "name": "Galaxy Fish shard",
    "metric": "Crop Yield",
    "modeScope": "Any",
    "cropScope": "Any",
    "status": "ACTIVE",
    "max": 10,
    "stepGain": 1,
    "manualDefault": null,
    "rawMarginal": 1,
    "hypercharge": false,
    "notes": "Ultimate DNA (shard L41) grants +1 Mining, Farming and Foraging Fortune per level, max +10 each. Only the Farming share is scored here.",
    "source": "https://hypixelskyblock.minecraft.wiki/w/Attributes",
    "lastVerified": "2026-09-16",
    "workbookRank": 37
  },
  {
    "id": "attribute-shard-earthworm-shard-formerly-termite",
    "attribute": "Infiltration",
    "category": "Attribute Shard",
    "section": "shards",
    "name": "Earthworm Shard (formerly Termite)",
    "metric": "Crop Yield",
    "modeScope": "Any",
    "cropScope": "Any",
    "status": "ACTIVE",
    "max": 10,
    "stepGain": 3,
    "manualDefault": null,
    "rawMarginal": 3,
    "hypercharge": false,
    "notes": "+3 FF per shard level, max +30 while your current Garden plot has a Pest; also applies when vacuuming Pest drops.",
    "source": "https://hypixel.net/threads/hypixel-skyblock-0-27-torrhus-canyon-critter-safari.6132090/",
    "lastVerified": "2026-09-16",
    "workbookRank": 33
  },
  {
    "id": "temporary-buff-pesthunter-phillip-buff",
    "category": "Temporary Buff",
    "section": "buffs",
    "name": "Pesthunter Phillip buff",
    "metric": "Crop Yield",
    "modeScope": "Any",
    "cropScope": "Any",
    "status": "ACTIVE",
    "max": 1,
    "stepGain": 200,
    "manualDefault": null,
    "rawMarginal": 200,
    "hypercharge": true,
    "notes": "+5 FF/pest, cap +200; Hypercharge can amplify it.",
    "source": "https://hypixel.net/threads/aug-3-0-27-alpha-changes-2.6134812/",
    "workbookRank": 2
  },
  {
    "id": "mixin-celestial-mason-jar",
    "category": "Mixin",
    "section": "buffs",
    "name": "Celestial Mason Jar",
    "metric": "Crop Yield",
    "modeScope": "Any",
    "cropScope": "Any",
    "status": "ACTIVE",
    "max": 1,
    "stepGain": 15,
    "manualDefault": null,
    "rawMarginal": 15,
    "hypercharge": true,
    "notes": "+15 FF on God Potion. Cookie permits direct consumption.",
    "source": "https://hypixel-skyblock.fandom.com/wiki/Celestial_Mason_Jar",
    "workbookRank": 19
  },
  {
    "id": "mixin-melon-juice-mixin",
    "category": "Mixin",
    "section": "buffs",
    "name": "Melon Juice Mixin",
    "metric": "Crop Yield",
    "modeScope": "Any",
    "cropScope": "Any",
    "status": "ACTIVE",
    "max": 1,
    "stepGain": 15,
    "manualDefault": null,
    "rawMarginal": 15,
    "hypercharge": false,
    "notes": "+15 FF on God Potion. Kept non-Hypercharge in this model pending behavior confirmation.",
    "source": "https://hypixel-skyblock.fandom.com/wiki/Melon_Juice_Mixin",
    "workbookRank": 20
  },
  {
    "id": "temporary-atmospheric-filter-spring",
    "physicalItemId": "ATMOSPHERIC_FILTER",
    "category": "Accessory",
    "section": "accessories",
    "name": "Atmospheric Filter (Spring)",
    "metric": "Crop Yield",
    "modeScope": "Any",
    "cropScope": "Any",
    "status": "ACTIVE",
    "max": 1,
    "stepGain": 25,
    "manualDefault": null,
    "rawMarginal": 25,
    "hypercharge": true,
    "notes": "+25 FF during Spring; Hypercharge-sensitive.",
    "source": "https://wiki.eliteskyblock.com/Farming_Fortune",
    "workbookRank": 16
  },
  {
    "id": "temporary-magic-8-ball-ff-roll",
    "physicalItemId": "MAGIC_8_BALL",
    "category": "Accessory",
    "section": "accessories",
    "name": "Magic 8 Ball FF roll",
    "metric": "Crop Yield",
    "modeScope": "Any",
    "cropScope": "Any",
    "status": "ACTIVE",
    "max": 1,
    "stepGain": 25,
    "manualDefault": null,
    "rawMarginal": 25,
    "hypercharge": true,
    "notes": "+25 FF when the Farming Fortune roll is active.",
    "source": "https://wiki.eliteskyblock.com/Farming_Fortune",
    "workbookRank": 17
  },
  {
    "id": "temporary-chocolate-century-cake",
    "category": "Temporary",
    "section": "buffs",
    "name": "Chocolate Century Cake",
    "metric": "Crop Yield",
    "modeScope": "Any",
    "cropScope": "Any",
    "status": "ACTIVE",
    "max": 1,
    "stepGain": 5,
    "manualDefault": null,
    "rawMarginal": 0,
    "hypercharge": true,
    "notes": "+5 FF while active; can be kept up nearly permanently.",
    "source": "https://wiki.eliteskyblock.com/Farming_Fortune",
    "workbookRank": null
  },
  {
    "id": "temporary-harvest-harbinger-v",
    "category": "Temporary",
    "section": "buffs",
    "name": "Harvest Harbinger V",
    "metric": "Crop Yield",
    "modeScope": "Any",
    "cropScope": "Any",
    "status": "ACTIVE",
    "max": 1,
    "stepGain": 50,
    "manualDefault": null,
    "rawMarginal": 50,
    "hypercharge": false,
    "notes": "+50 FF potion effect; model excludes Hypercharge interaction.",
    "source": "https://wiki.eliteskyblock.com/Farming_Fortune",
    "workbookRank": 10
  },
  {
    "id": "harvest-feast-fortunate-feasting-v",
    "category": "Harvest Feast",
    "section": "buffs",
    "name": "Fortunate Feasting V",
    "metric": "Crop Yield",
    "modeScope": "Harvest Feast",
    "cropScope": "Any",
    "status": "ACTIVE",
    "max": 5,
    "stepGain": 5,
    "manualDefault": null,
    "rawMarginal": 5,
    "hypercharge": false,
    "notes": "+5 FF per Carnival perk tier, max +25 during Harvest Feast.",
    "source": "https://hypixel.net/threads/march-31-harvest-feast-event.6080784/",
    "workbookRank": null
  },
  {
    "id": "garden-chip-rarefinder-chip",
    "packAsset": "rarefinder_chip",
    "category": "Garden Chip",
    "section": "chips",
    "name": "Rarefinder Chip",
    "metric": "Rare Crops",
    "modeScope": "Any",
    "cropScope": "Any",
    "status": "ACTIVE",
    "max": 20,
    "stepGain": 2.5,
    "manualDefault": null,
    "rawMarginal": 2.5,
    "hypercharge": false,
    "notes": "0.26.1 max is +50 Overbloom. Adjust marginal step for current rarity.",
    "source": "https://hypixel.net/threads/hypixel-skyblock-0-26-1-new-player-improvements-harvest-feast-changes-healing-revamp-and-more.6127383/",
    "workbookRank": null
  },
  {
    "id": "consumable-feast-burger-permanent-overbloom",
    "category": "Consumable",
    "section": "account",
    "name": "Feast Burger permanent Overbloom",
    "metric": "Rare Crops",
    "modeScope": "Any",
    "cropScope": "Any",
    "status": "ACTIVE",
    "max": 5,
    "stepGain": 1,
    "manualDefault": null,
    "rawMarginal": 1,
    "hypercharge": false,
    "notes": "+1 permanent Overbloom per use, up to 5.",
    "source": "https://hypixel.net/threads/hypixel-skyblock-0-26-1-new-player-improvements-harvest-feast-changes-healing-revamp-and-more.6127383/",
    "workbookRank": null
  },
  {
    "id": "pet-item-lucky-clover-poignant-lucky-clover",
    "category": "Pet Item",
    "section": "pets",
    "name": "Lucky Clover / Poignant Lucky Clover",
    "metric": "Rare Crops",
    "modeScope": "Any",
    "cropScope": "Any",
    "status": "ACTIVE",
    "max": 1,
    "stepGain": 13,
    "manualDefault": null,
    "rawMarginal": 13,
    "hypercharge": false,
    "notes": "Poignant Lucky Clover now gives +13 Overbloom; mutually exclusive pet item.",
    "source": "https://hypixel.net/threads/hypixel-skyblock-0-26-1-new-player-improvements-harvest-feast-changes-healing-revamp-and-more.6127383/",
    "workbookRank": null
  },
  {
    "id": "armor-enchant-sunset-v-day-overbloom",
    "category": "Armor Enchant",
    "section": "gear",
    "name": "Sunset V (day Overbloom)",
    "metric": "Rare Crops",
    "modeScope": "Any",
    "cropScope": "Any",
    "status": "ACTIVE",
    "max": 5,
    "stepGain": 1,
    "manualDefault": null,
    "rawMarginal": 1,
    "hypercharge": false,
    "notes": "+1 Overbloom per tier during day, max +5; revamped from Moonlit.",
    "source": "https://hypixel.net/threads/april-21-fossil-essence-shop-farming-toolkit-harvest-feast-changes.6083245/",
    "workbookRank": null
  },
  {
    "id": "harvest-feast-grand-feast-rare-crop-bonus",
    "category": "Harvest Feast",
    "section": "buffs",
    "name": "Grand Feast rare-crop bonus",
    "metric": "Rare Crops",
    "modeScope": "Harvest Feast",
    "cropScope": "Any",
    "status": "VERIFY",
    "max": 1,
    "stepGain": 5,
    "manualDefault": null,
    "rawMarginal": 5,
    "hypercharge": false,
    "notes": "Event progression can grant +5% rare crop chance for the rest of Grand Feast.",
    "source": "https://hypixel.net/threads/march-31-harvest-feast-event.6080784/",
    "workbookRank": null
  },
  {
    "id": "pest-pesthunter-accessory-bpc-setup",
    "category": "Pest",
    "section": "pests",
    "name": "Pesthunter accessory / BPC setup",
    "metric": "Pest Spawn",
    "modeScope": "Pest Spawning",
    "cropScope": "Any",
    "status": "VERIFY",
    "max": 1,
    "stepGain": 0,
    "manualDefault": null,
    "rawMarginal": 0,
    "hypercharge": false,
    "notes": "Bonus Pest Chance sources are setup-dependent. Enter marginal BPC manually.",
    "source": "https://hypixel.net/threads/april-21-fossil-essence-shop-farming-toolkit-harvest-feast-changes.6083245/",
    "workbookRank": null
  },
  {
    "id": "harvest-feast-feast-crashers-iii",
    "category": "Harvest Feast",
    "section": "buffs",
    "name": "Feast Crashers III",
    "metric": "Pest Spawn",
    "modeScope": "Harvest Feast",
    "cropScope": "Any",
    "status": "ACTIVE",
    "max": 3,
    "stepGain": 2,
    "manualDefault": null,
    "rawMarginal": 2,
    "hypercharge": false,
    "notes": "+2 BPC per Carnival perk tier, max +6.",
    "source": "https://hypixel.net/threads/march-31-harvest-feast-event.6080784/",
    "workbookRank": null
  },
  {
    "id": "armor-helianthus-armor-bpc",
    "category": "Armor",
    "section": "gear",
    "name": "Helianthus armor BPC",
    "metric": "Pest Spawn",
    "modeScope": "Pest Spawning",
    "cropScope": "Any",
    "status": "ACTIVE",
    "max": 1,
    "stepGain": 80,
    "manualDefault": null,
    "rawMarginal": 80,
    "hypercharge": false,
    "notes": "Full Helianthus set shows +80 Bonus Pest Chance base.",
    "source": "https://hypixel-skyblock.fandom.com/wiki/Helianthus_Armor",
    "workbookRank": null
  },
  {
    "id": "buff-booster-cookie-farming-wisdom-contribution",
    "category": "Buff",
    "section": "buffs",
    "name": "Booster Cookie Farming Wisdom contribution",
    "metric": "Farming XP",
    "modeScope": "Any",
    "cropScope": "Any",
    "status": "VERIFY",
    "max": 1,
    "stepGain": 0,
    "manualDefault": null,
    "rawMarginal": 0,
    "hypercharge": false,
    "notes": "Enter the current Farming Wisdom shown by your active Cookie/profile if optimizing XP.",
    "source": "https://hypixel-skyblock.fandom.com/wiki/Farming_Fortune",
    "workbookRank": null
  },
  {
    "id": "pet-rabbit-xp-pet-switch",
    "category": "Pet",
    "section": "pets",
    "name": "Rabbit/XP pet switch",
    "metric": "Farming XP",
    "modeScope": "Any",
    "cropScope": "Any",
    "status": "VERIFY",
    "max": 1,
    "stepGain": 0,
    "manualDefault": null,
    "rawMarginal": 0,
    "hypercharge": false,
    "notes": "Pet XP/wisdom value is mutually exclusive with fortune pets; enter net marginal Wisdom manually.",
    "source": "https://hypixel-skyblock.fandom.com/wiki/Farming_Fortune",
    "workbookRank": null
  },
  {
    "id": "mixin-celestial-mason-jar-wisdom",
    "category": "Mixin",
    "section": "buffs",
    "name": "Celestial Mason Jar Wisdom",
    "metric": "Farming XP",
    "modeScope": "Any",
    "cropScope": "Any",
    "status": "ACTIVE",
    "max": 1,
    "stepGain": 3,
    "manualDefault": null,
    "rawMarginal": 3,
    "hypercharge": false,
    "notes": "Mason Jar also grants +3 Wisdom.",
    "source": "https://hypixel-skyblock.fandom.com/wiki/Celestial_Mason_Jar",
    "workbookRank": null
  },
  {
    "id": "pet-orchid-mantis-intelligent-specimen",
    "category": "Pet",
    "section": "pets",
    "name": "Orchid Mantis - Intelligent Specimen",
    "metric": "Tool XP",
    "modeScope": "Any",
    "cropScope": "Any",
    "status": "ACTIVE",
    "max": 1,
    "stepGain": 20,
    "manualDefault": null,
    "rawMarginal": 20,
    "hypercharge": false,
    "notes": "At max pet level, Intelligent Specimen grants +20% Farming Tool Exp. This is separate from Farming Wisdom.",
    "source": "https://hypixel.net/threads/hypixel-skyblock-0-26-1-new-player-improvements-harvest-feast-changes-healing-revamp-and-more.6127383/",
    "workbookRank": null
  },
  {
    "id": "garden-chip-overdrive-chip",
    "packAsset": "overdrive_chip",
    "category": "Garden Chip",
    "section": "chips",
    "name": "Overdrive Chip",
    "metric": "Crop Yield",
    "modeScope": "Jacob Contest",
    "cropScope": "Any",
    "status": "ACTIVE",
    "max": 20,
    "stepGain": 7,
    "manualDefault": null,
    "rawMarginal": 7,
    "hypercharge": false,
    "notes": "Legendary in-menu scaling: +7 Farming Fortune per level for crops active in the current Jacob's Contest; max level 20. Use manual override for Rare/Epic scaling.",
    "source": "https://hypixel.net/threads/list-of-item-in-skyblock-major-update.6123513/",
    "workbookRank": null
  },
  {
    "id": "garden-chip-quickdraw-chip",
    "packAsset": "quickdraw_chip",
    "category": "Garden Chip",
    "section": "chips",
    "name": "Quickdraw Chip",
    "metric": "Visitor Speed",
    "modeScope": "Any",
    "cropScope": "Any",
    "status": "ACTIVE",
    "max": 20,
    "stepGain": 2.5,
    "manualDefault": null,
    "rawMarginal": 2.5,
    "hypercharge": false,
    "notes": "Legendary in-menu scaling: -2.5% Visitor cooldown per level. Visitor-rate gain is non-linear and is calculated from current cooldown reduction.",
    "source": "https://hypixel.net/threads/list-of-item-in-skyblock-major-update.6123513/",
    "workbookRank": null
  },
  {
    "id": "garden-chip-synthesis-chip",
    "packAsset": "synthesis_chip",
    "category": "Garden Chip",
    "section": "chips",
    "name": "Synthesis Chip",
    "metric": "Copper Rewards",
    "modeScope": "Greenhouse",
    "cropScope": "Any",
    "status": "ACTIVE",
    "max": 20,
    "stepGain": 2,
    "manualDefault": null,
    "rawMarginal": 2,
    "hypercharge": false,
    "notes": "Legendary in-menu scaling: +2% base Copper rewards from the Crop Analyzer per level.",
    "source": "https://hypixel.net/threads/list-of-item-in-skyblock-major-update.6123513/",
    "workbookRank": null
  },
  {
    "id": "garden-chip-evergreen-chip",
    "packAsset": "evergreen_chip",
    "category": "Garden Chip",
    "section": "chips",
    "name": "Evergreen Chip",
    "metric": "Greenhouse Yield",
    "modeScope": "Greenhouse",
    "cropScope": "Any",
    "status": "ACTIVE",
    "max": 20,
    "stepGain": 3,
    "manualDefault": null,
    "rawMarginal": 3,
    "hypercharge": false,
    "notes": "Legendary in-menu scaling: +3% base crop harvests from crops and mutations in the Greenhouse per level.",
    "source": "https://hypixel.net/threads/list-of-item-in-skyblock-major-update.6123513/",
    "workbookRank": null
  },
  {
    "id": "garden-chip-vermin-vaporizer-chip",
    "packAsset": "vermin_vaporizer_chip",
    "category": "Garden Chip",
    "section": "chips",
    "name": "Vermin Vaporizer Chip",
    "metric": "Pest Spawn",
    "modeScope": "Pest Spawning",
    "cropScope": "Any",
    "status": "ACTIVE",
    "max": 20,
    "stepGain": 5,
    "manualDefault": null,
    "rawMarginal": 5,
    "hypercharge": false,
    "notes": "Legendary in-menu scaling: +5 Bonus Pest Chance per level; max +100 BPC.",
    "source": "https://hypixel.net/threads/list-of-item-in-skyblock-major-update.6123513/",
    "workbookRank": null
  },
  {
    "id": "garden-chip-mechamind-chip",
    "packAsset": "mechamind_chip",
    "category": "Garden Chip",
    "section": "chips",
    "name": "Mechamind Chip",
    "metric": "Tool XP",
    "modeScope": "Any",
    "cropScope": "Any",
    "status": "ACTIVE",
    "max": 20,
    "stepGain": 2.5,
    "manualDefault": null,
    "rawMarginal": 2.5,
    "hypercharge": false,
    "notes": "Legendary in-menu scaling: +2.5% Farming Tool experience per level.",
    "source": "https://hypixel.net/threads/list-of-item-in-skyblock-major-update.6123513/",
    "workbookRank": null
  },
  {
    "id": "garden-chip-sowledge-chip",
    "packAsset": "sowledge_chip",
    "category": "Garden Chip",
    "section": "chips",
    "name": "Sowledge Chip",
    "metric": "Farming XP",
    "modeScope": "Any",
    "cropScope": "Any",
    "status": "ACTIVE",
    "max": 20,
    "stepGain": 1.5,
    "manualDefault": null,
    "rawMarginal": 1.5,
    "hypercharge": false,
    "notes": "Legendary in-menu scaling: +1.5 Farming Wisdom per level; max +30.",
    "source": "https://hypixel.net/threads/list-of-item-in-skyblock-major-update.6123513/",
    "workbookRank": null
  },
  {
    "id": "equipment-reforge-thorny-on-full-mythic-equipment-ff",
    "category": "Equipment Reforge",
    "section": "gear",
    "name": "Thorny on full Mythic equipment - FF",
    "metric": "Crop Yield",
    "modeScope": "Any",
    "cropScope": "Any",
    "status": "ACTIVE",
    "max": 1,
    "stepGain": 48,
    "manualDefault": null,
    "rawMarginal": 48,
    "hypercharge": false,
    "notes": "Blooming Thorns gives up to +12 FF per Mythic equipment piece. Full four-piece reference +48. Replaces Rooted, so use manual marginal override for an actual swap.",
    "source": "https://hypixel.net/threads/list-of-item-in-skyblock-update-1-81.6151548/",
    "workbookRank": 12
  },
  {
    "id": "equipment-reforge-thorny-on-full-mythic-equipment-overbloom",
    "category": "Equipment Reforge",
    "section": "gear",
    "name": "Thorny on full Mythic equipment - Overbloom",
    "metric": "Rare Crops",
    "modeScope": "Any",
    "cropScope": "Any",
    "status": "ACTIVE",
    "max": 1,
    "stepGain": 6,
    "manualDefault": null,
    "rawMarginal": 6,
    "hypercharge": false,
    "notes": "Up to +1.5 Overbloom per Mythic piece = +6 on four pieces, before the separate Thorny Bonus from Thorns tiers. Replaces Rooted.",
    "source": "https://hypixel.net/threads/list-of-item-in-skyblock-update-1-81.6151548/",
    "workbookRank": null
  },
  {
    "id": "attribute-shard-field-mouse-shard-pest-overbloom",
    "attribute": "Pest Luck",
    "category": "Attribute Shard",
    "section": "shards",
    "name": "Field Mouse Shard - Pest Overbloom",
    "metric": "Rare Crops",
    "modeScope": "Pest Vacuum Drops",
    "cropScope": "Any",
    "status": "ACTIVE",
    "max": 10,
    "stepGain": 0.5,
    "manualDefault": null,
    "rawMarginal": 0.5,
    "hypercharge": false,
    "notes": "0.27 standardized the shard to +0.5-5 Overbloom on Pests.",
    "source": "https://hypixel.net/threads/hypixel-skyblock-0-27-torrhus-canyon-critter-safari.6132090/",
    "lastVerified": "2026-09-16",
    "workbookRank": null
  },
  {
    "id": "vacuum-reforge-beady-pest-only-farming-fortune",
    "category": "Vacuum Reforge",
    "section": "tools",
    "name": "Beady - Pest-only Farming Fortune",
    "metric": "Crop Yield",
    "modeScope": "Pest Vacuum Drops",
    "cropScope": "Any",
    "status": "ACTIVE",
    "max": 1,
    "stepGain": 100,
    "manualDefault": null,
    "rawMarginal": 100,
    "hypercharge": false,
    "notes": "Beady vacuum reforge grants +100 Farming Fortune on Pests. Pest drop scaling uses /600, not the normal crop /100 scaling.",
    "source": "https://hypixel-skyblock.fandom.com/wiki/Module:Inventory_slot/Tooltips",
    "workbookRank": null
  },
  {
    "id": "temporary-buff-refined-dark-cacao-truffle-temporary-stack",
    "category": "Temporary Buff",
    "section": "buffs",
    "name": "Refined Dark Cacao Truffle temporary stack",
    "metric": "Crop Yield",
    "modeScope": "Any",
    "cropScope": "Cocoa Beans",
    "status": "ACTIVE",
    "max": 1,
    "stepGain": 30,
    "manualDefault": null,
    "rawMarginal": 30,
    "hypercharge": true,
    "notes": "Temporary cocoa-only Fortune stack. 0.27 changed Dark Cacao from Global Fortune to Cocoa Fortune. Hypercharge-eligible.",
    "source": "https://hypixel.net/threads/hypixel-skyblock-0-27-torrhus-canyon-critter-safari.6132090/",
    "workbookRank": null
  },
  {
    "id": "attribute-shard-cricket-pest-fortune",
    "attribute": "Pest Fortune",
    "category": "Attribute Shard",
    "section": "shards",
    "name": "Cricket Shard - Pest Fortune",
    "metric": "Crop Yield",
    "modeScope": "Pest Vacuum Drops",
    "cropScope": "Any",
    "status": "ACTIVE",
    "max": 10,
    "stepGain": 5,
    "manualDefault": null,
    "rawMarginal": 5,
    "hypercharge": false,
    "notes": "+5 Farming Fortune per level, max +50, on Pests only (shard U19). Pest drops scale /600, not the normal crop /100, so this is worth far less than the same Fortune on crops.",
    "source": "https://hypixelskyblock.minecraft.wiki/w/Attributes",
    "lastVerified": "2026-09-16",
    "workbookRank": null
  },
  {
    "id": "attribute-shard-keeled-slug-bonus-pest-chance",
    "attribute": "Bonus Pest Chance",
    "category": "Attribute Shard",
    "section": "shards",
    "name": "Keeled Slug Shard - Bonus Pest Chance",
    "metric": "Pest Spawn",
    "modeScope": "Pest Spawning",
    "cropScope": "Any",
    "status": "ACTIVE",
    "max": 10,
    "stepGain": 1,
    "manualDefault": null,
    "rawMarginal": 1,
    "hypercharge": false,
    "notes": "+1 Bonus Pest Chance per level, max +10 (shard U94). Only useful while deliberately farming Pests.",
    "source": "https://hypixelskyblock.minecraft.wiki/w/Attributes",
    "lastVerified": "2026-09-16",
    "workbookRank": null
  },
  {
    "id": "attribute-shard-rat-sprayonator-serendipity",
    "attribute": "Sprayonator Serendipity",
    "category": "Attribute Shard",
    "section": "shards",
    "name": "Rat Shard - Sprayonator Serendipity",
    "metric": "Sprayonator Materials",
    "modeScope": "Pest Vacuum Drops",
    "cropScope": "Any",
    "status": "ACTIVE",
    "max": 10,
    "stepGain": 1,
    "manualDefault": null,
    "rawMarginal": 1,
    "hypercharge": false,
    "notes": "+1% chance per level, max +10%, for a Pest to drop an extra Sprayonator Material (shard U91). Saves Sprayonator upkeep; it adds no Farming Fortune.",
    "source": "https://hypixelskyblock.minecraft.wiki/w/Attributes",
    "lastVerified": "2026-09-16",
    "workbookRank": null
  },
  {
    "id": "attribute-shard-mosquito-enchanted-farmer",
    "attribute": "Enchanted Farmer",
    "category": "Attribute Shard",
    "section": "shards",
    "name": "Mosquito Shard - Enchanted Farmer",
    "metric": "Enchanted Crops",
    "modeScope": "Any",
    "cropScope": "Any",
    "status": "ACTIVE",
    "max": 10,
    "stepGain": 0.001,
    "manualDefault": null,
    "rawMarginal": 0.001,
    "hypercharge": false,
    "notes": "+0.001% chance per level, max +0.01%, to find an Enchanted Crop while farming (shard U103). Deliberately kept at its real magnitude: at max level this is one extra Enchanted Crop per 10,000 breaks, so it ranks last.",
    "source": "https://hypixelskyblock.minecraft.wiki/w/Attributes",
    "lastVerified": "2026-09-16",
    "workbookRank": null
  },
  {
    "id": "attribute-shard-mudworm-visitor-bait",
    "attribute": "Visitor Bait",
    "category": "Attribute Shard",
    "section": "shards",
    "name": "Mudworm Shard - Visitor Bait",
    "metric": "Visitor Speed",
    "modeScope": "Any",
    "cropScope": "Any",
    "status": "ACTIVE",
    "max": 10,
    "stepGain": 1,
    "manualDefault": null,
    "rawMarginal": 1,
    "hypercharge": false,
    "notes": "Garden Visitors arrive +1% faster per level, max +10% (shard C25). Stacks with the Quickdraw Chip but is a different stat: this is arrival rate, Quickdraw is cooldown reduction.",
    "source": "https://hypixelskyblock.minecraft.wiki/w/Attributes",
    "lastVerified": "2026-09-16",
    "workbookRank": null
  },
  {
    "id": "attribute-shard-invisibug-fancy-visit",
    "attribute": "Fancy Visit",
    "category": "Attribute Shard",
    "section": "shards",
    "name": "Invisibug Shard - Fancy Visit",
    "metric": "Visitor Rarity",
    "modeScope": "Any",
    "cropScope": "Any",
    "status": "ACTIVE",
    "max": 10,
    "stepGain": 1,
    "manualDefault": null,
    "rawMarginal": 1,
    "hypercharge": false,
    "notes": "+1% chance per level, max +10%, that a RARE or better Garden Visitor arrives (shard R10). Changes visitor rarity, not visitor speed.",
    "source": "https://hypixelskyblock.minecraft.wiki/w/Attributes",
    "lastVerified": "2026-09-16",
    "workbookRank": null
  },
  {
    "id": "attribute-shard-dragonfly-garden-wisdom",
    "attribute": "Garden Wisdom",
    "category": "Attribute Shard",
    "section": "shards",
    "name": "Dragonfly Shard - Garden Wisdom",
    "metric": "Farming XP",
    "modeScope": "Any",
    "cropScope": "Any",
    "status": "ACTIVE",
    "max": 10,
    "stepGain": 0.5,
    "manualDefault": null,
    "rawMarginal": 0.5,
    "hypercharge": false,
    "notes": "+0.5 Farming Wisdom per level, max +5 (shard E37). Wisdom is an XP multiplier, so this matters while levelling Farming and not at all for coins.",
    "source": "https://hypixelskyblock.minecraft.wiki/w/Attributes",
    "lastVerified": "2026-09-16",
    "workbookRank": null
  },
  {
    "id": "attribute-shard-moth-pest-cooldown",
    "attribute": "Pest Cooldown",
    "category": "Attribute Shard",
    "section": "shards",
    "name": "Moth Shard - Pest Cooldown",
    "metric": "Pest Spawn",
    "modeScope": "Pest Spawning",
    "cropScope": "Any",
    "status": "VERIFY",
    "max": 10,
    "stepGain": 0,
    "manualDefault": null,
    "rawMarginal": 0,
    "hypercharge": false,
    "notes": "Reduces the Pest spawn cooldown by 0.5s (shard U100). The wiki prints this flat figure with no per-level range on either the attribute list or the shard page, unlike every other farming attribute, so no per-level value is stored. Enter the reduction you actually see in-game.",
    "source": "https://hypixelskyblock.minecraft.wiki/w/Moth_Shard",
    "lastVerified": "2026-09-16",
    "workbookRank": null
  }
];

export const HIDDEN_INTERACTIONS = [
  {
    "id": "normal-crop-drops",
    "name": "Normal crop drops",
    "effect": "Average drops = Base \u00d7 (1 + (Global FF + Crop Fortune) / 100)",
    "why": "An additive +X FF has diminishing relative value as existing Fortune rises.",
    "handling": "Upgrades \u2192 Relative gain = marginal FF / (100 + current effective Fortune).",
    "status": "ACTIVE",
    "source": "https://wiki.eliteskyblock.com/Farming_Fortune"
  },
  {
    "id": "pest-vacuum-drops",
    "name": "Pest vacuum drops",
    "effect": "Drop multiplier = 1 + (Global FF + Crop Fortune + Pest-only FF) / 600",
    "why": "Pest drop Fortune is six times less sensitive than normal crop drops; Beady / pet pest-only FF belongs here.",
    "handling": "Use Mode = Pest Vacuum Drops. Inputs row 25 stores pest-only Fortune.",
    "status": "ACTIVE",
    "source": "https://wiki.eliteskyblock.com/Introduction_to_Pest_Farming"
  },
  {
    "id": "cropeetle-shard-crop-bug",
    "name": "Cropeetle Shard \u2014 Crop Bug",
    "effect": "+2% per level, up to +20% odds for Cropie / Squash / Fermento-type armor rare drops.",
    "why": "This is a multiplicative/special rare-drop modifier, not ordinary additive FF.",
    "handling": "Documented separately; do not convert +20% into +20 FF. For a dedicated rare-armor-drop comparison, use the actual drop-rate multiplier.",
    "status": "ACTIVE",
    "source": "https://hypixel-skyblock.fandom.com/wiki/Attributes"
  },
  {
    "id": "rose-dragon-rare-drop-perk",
    "name": "Rose Dragon \u2014 rare-drop perk",
    "effect": "Max-level pet has a separate rare-crop/drop modifier in addition to its Farming Fortune and Copper perks.",
    "why": "Community pages/lore representations changed around the Overbloom rollout; stacking it as plain FF would be wrong.",
    "handling": "Pet_Calculator ranks its FF contribution only. Treat rare-drop/Copper value as an additional benefit; verify current in-game tooltip for the exact rare-drop wording.",
    "status": "VERIFY",
    "source": "https://skyah.net/item/PET_ROSE_DRAGON"
  },
  {
    "id": "rarefinder-chip",
    "name": "Rarefinder Chip",
    "effect": "Legendary scaling +2.5 Overbloom per level; max +50 after 0.26.1.",
    "why": "Older guides still show +60. Newer official patch value overrides them.",
    "handling": "Rank through Metric = Rare Crops; do not use old +60 tables.",
    "status": "ACTIVE",
    "source": "https://hypixel.net/threads/hypixel-skyblock-0-26-1-new-player-improvements-harvest-feast-changes-healing-revamp-and-more.6127383/"
  },
  {
    "id": "juicy-salty-sprayonator",
    "name": "Juicy / Salty Sprayonator",
    "effect": "Juicy: 45 min and x3 materials for x2 base effects. Salty: 60 min and x5 materials for x3 base effects.",
    "why": "Nozzle value scales the selected spray material's base effect rather than adding one universal stat.",
    "handling": "Apply the resulting in-game BPC/FF/other spray effect to Inputs or the relevant buff row; do not hard-code one universal Fortune value.",
    "status": "ACTIVE",
    "source": "https://hypixel.net/threads/hypixel-skyblock-0-26-1-new-player-improvements-harvest-feast-changes-healing-revamp-and-more.6127383/"
  },
  {
    "id": "buzzybee-s-fantabulous-disco-destination",
    "name": "Buzzybee's Fantabulous Disco Destination",
    "effect": "Re-added in 0.26.1 flow for offline Pests only.",
    "why": "Offline corral behavior is utility, not directly comparable to additive FF/BPC.",
    "handling": "Keep outside numeric FF ranking; value by your pest workflow.",
    "status": "ACTIVE",
    "source": "https://hypixel.net/threads/july-20-0-26-1-alpha-changes.6127303/"
  },
  {
    "id": "ladybug-shard-pretty-clothes",
    "name": "Ladybug Shard \u2014 Pretty Clothes",
    "effect": "+1% Copper from Garden Visitors per level, up to +10%.",
    "why": "Affects Copper rewards, not crop yield.",
    "handling": "Use as a separate visitor-economy multiplier; do not add to Farming Fortune.",
    "status": "ACTIVE",
    "source": "https://hypixel-skyblock.fandom.com/wiki/Attributes"
  },
  {
    "id": "invisibug-shard-fancy-visit",
    "name": "Invisibug Shard \u2014 Fancy Visit",
    "effect": "+1% chance per level for RARE+ Garden Visitors, up to +10%.",
    "why": "Changes visitor rarity distribution rather than cooldown.",
    "handling": "Do not combine with Quickdraw as if both were the same visitor-speed stat. Fancy Visit and Visitor Bait are now separate scored shard entries with separate metrics (Visitor Rarity and Visitor Speed).",
    "status": "ACTIVE",
    "lastVerified": "2026-09-16",
    "source": "https://hypixelskyblock.minecraft.wiki/w/Attributes"
  },
  {
    "id": "hypercharge-chip",
    "name": "Hypercharge Chip",
    "effect": "Boosts only explicitly eligible temporary Farming-Fortune buffs; not every temporary-looking effect.",
    "why": "Its marginal value depends on which eligible buffs are active at that moment.",
    "handling": "Buffs sheet totals eligible base FF; Upgrades row for Hypercharge uses Active eligible FF \u00d7 next chip increment.",
    "status": "ACTIVE",
    "source": "https://hypixel.net/threads/april-21-fossil-essence-shop-farming-toolkit-harvest-feast-changes.6083245/"
  },
  {
    "id": "god-potion-celestial-mason-jar-melon-juice-cookie",
    "name": "God Potion / Celestial Mason Jar / Melon Juice / Cookie",
    "effect": "Mason Jar adds +15 FF (+3 Wisdom) to God Potion; Melon Juice adds +15 FF. Cookie allows direct Mixin consumption.",
    "why": "God Pot/Boosters also change Strength/Speed, which can alter Mooshroom Cow / Orchid Mantis contribution.",
    "handling": "Enter actual Strength/Speed in Inputs. Toggle direct FF buffs in Buffs; Cookie itself is not treated as flat FF.",
    "status": "ACTIVE",
    "source": "https://hypixel-skyblock.fandom.com/wiki/Celestial_Mason_Jar"
  },
  {
    "id": "mooshroom-cow",
    "name": "Mooshroom Cow",
    "effect": "Base FF plus Strength-dependent Farming Strength conversion.",
    "why": "God Pot / accessories / attributes can change Strength and therefore pet FF indirectly.",
    "handling": "Pet_Calculator recomputes from actual farming Strength instead of assigning a single static pet value.",
    "status": "ACTIVE",
    "source": "https://hypixel.net/threads/hypixel-skyblock-0-26-1-new-player-improvements-harvest-feast-changes-healing-revamp-and-more.6127383/"
  },
  {
    "id": "orchid-mantis",
    "name": "Orchid Mantis",
    "effect": "Swift Sickles grants up to +1 FF per 3 Speed; Intelligent Specimen up to +20% Farming Tool Exp.",
    "why": "One pet affects both FF and Tool XP through different mechanics.",
    "handling": "Pet_Calculator handles Speed\u2192FF; Upgrades contains Tool XP separately.",
    "status": "ACTIVE",
    "source": "https://hypixel.net/threads/hypixel-skyblock-0-26-1-new-player-improvements-harvest-feast-changes-healing-revamp-and-more.6127383/"
  },
  {
    "id": "rooted-thorny-equipment",
    "name": "Rooted \u2194 Thorny equipment",
    "effect": "Both occupy the equipment reforge slot. Thorny supplies FF + Overbloom; Rooted is a competing reforge.",
    "why": "Their headline totals cannot be stacked.",
    "handling": "Enter the actual net swap delta in Manual marginal override rather than the full new reforge total.",
    "status": "ACTIVE",
    "source": "https://hypixel.net/threads/list-of-item-in-skyblock-update-1-81.6151548/"
  },
  {
    "id": "blessed-bountiful-tool-reforge",
    "name": "Blessed \u2194 Bountiful tool reforge",
    "effect": "Mutually exclusive tool reforges; Bountiful can have coin-value benefits despite lower FF.",
    "why": "Highest FF is not necessarily highest coins/hour.",
    "handling": "Use net FF swap delta for crop-yield ranking. Coin-profit optimization needs crop price and Bountiful coin proc economics outside this sheet.",
    "status": "ACTIVE",
    "source": "https://wiki.eliteskyblock.com/Farming_Fortune"
  },
  {
    "id": "firefly-lunar-moth",
    "name": "Firefly / Lunar Moth",
    "effect": "Day/night conditional Fortune; Garden time can make one condition effectively persistent for a chosen setup.",
    "why": "Whether +50 is active depends on current Garden time.",
    "handling": "Toggle only the shard matching the time state you actually farm in; never stack both simultaneously.",
    "status": "ACTIVE",
    "source": "https://eliteskyblock.com/articles/news-foraging-and-hunting-update"
  },
  {
    "id": "earthworm-shard-formerly-termite",
    "name": "Earthworm Shard (formerly Termite)",
    "effect": "Up to +30 FF while the current Garden plot contains a Pest; also relevant when vacuuming that plot's pest.",
    "why": "Conditional on plot state rather than simply owning the shard.",
    "handling": "Toggle in Buffs only when the current plot condition is maintained.",
    "status": "ACTIVE",
    "source": "https://hypixel.net/threads/hypixel-skyblock-0-27-torrhus-canyon-critter-safari.6132090/"
  },
  {
    "id": "dark-cacao",
    "name": "Dark Cacao",
    "effect": "0.27 changed its Fortune from global to Cocoa Fortune.",
    "why": "Older guides can overstate every other crop by treating it as global.",
    "handling": "Workbook scopes both permanent and temporary Dark Cacao rows to Cocoa Beans.",
    "status": "ACTIVE",
    "source": "https://hypixel.net/threads/hypixel-skyblock-0-27-torrhus-canyon-critter-safari.6132090/"
  },
  {
    "id": "sunder-enchantment",
    "name": "Sunder enchantment",
    "effect": "Removed during the 2026 Farming Tool / Harvest Feast changes; axes and hoes share the Farming Tool path.",
    "why": "Old axe maxing lists that still include Sunder are obsolete.",
    "handling": "Excluded from upgrade ranking; Harvesting is used instead.",
    "status": "REMOVED",
    "source": "https://hypixel.net/threads/march-31-harvest-feast-event.6080784/"
  },
  {
    "id": "zorro-cape-claim-timing",
    "name": "Zorro's Cape is checked when contest rewards are claimed",
    "effect": "Zorro's Cape gives a 20% chance for an extra Jacob's Contest Medal, and that roll happens at the moment the reward is CLAIMED, not while the contest runs.",
    "why": "It means the Cape never has to be worn during the contest itself, so it costs nothing in farming stats. Equipping it only to claim is strictly better than not owning it, and the planner must not treat it as competing with the contest setup.",
    "handling": "Model as a claim-time multiplier on medal rewards, independent of the contest loadout. Never subtract contest Fortune for wearing it.",
    "status": "ACTIVE",
    "source": "https://hypixelskyblock.minecraft.wiki/w/Tutorial:Farming_Guide",
    "lastVerified": "2026-09-16"
  },
  {
    "id": "garden-time-freeze-one-shard",
    "name": "Freezing Garden time removes the need for both day and night shards",
    "effect": "Solar Power (Firefly Shard) gives Farming Fortune during the day and Lunar Power (Lunar Moth Shard) at night. Once both a Day Saver and a Night Saver have been given to the Garden, the Desk's Island Time setting freezes the Garden in one period.",
    "why": "A frozen Garden makes one of the two shards permanently useless, so buying and levelling both is wasted coins for ordinary farming. Only Moonflower farming actually needs Lunar Power.",
    "handling": "Treat Solar Power and Lunar Power as mutually exclusive once time is frozen, and never add both. Recommend whichever shard is cheaper unless the target crop is Moonflower.",
    "status": "ACTIVE",
    "source": "https://hypixelskyblock.minecraft.wiki/w/Tutorial:Farming_Guide",
    "lastVerified": "2026-09-16"
  },
  {
    "id": "bonus-pest-chance-integer-remainder",
    "name": "Bonus Pest Chance is a guaranteed count plus a remainder",
    "effect": "Each full 100 Bonus Pest Chance guarantees one additional Pest per spawn; the leftover amount is the percent chance of one more. 304 Bonus Pest Chance is four guaranteed Pests and a 4% chance of a fifth.",
    "why": "The value is a step function, not linear. Going from 299 to 300 adds a whole guaranteed Pest, while 300 to 399 adds almost nothing. Ranking this stat by raw points would be badly wrong.",
    "handling": "Evaluate Bonus Pest Chance in steps of 100 and show the distance to the next whole step. Never interpolate it linearly.",
    "status": "ACTIVE",
    "source": "https://hypixelskyblock.minecraft.wiki/w/Tutorial:Farming_Guide",
    "lastVerified": "2026-09-16"
  },
  {
    "id": "pest-fortune-penalty",
    "name": "Pests cut Farming Fortune, and 300+ Bonus Pest Chance softens it",
    "effect": "With 4 or more Pests on the Garden, Farming Fortune and every crop-specific Fortune is reduced, first by 5% and then in multiples of 15%, to a maximum 75% loss at the 8-Pest cap. Each full 100 Bonus Pest Chance allows one more Pest before the reduction begins, so at 300-399 Bonus Pest Chance eight active Pests cost only 15% Fortune.",
    "why": "This is a large negative term with no analogue anywhere else in the model. It also inverts a strategy: with enough Bonus Pest Chance, letting Pests build up becomes viable for low-attention farming instead of ruinous.",
    "handling": "Model expected Pest count and apply the reduction to the Fortune total BEFORE computing yield. Profit for a pest-tolerant setup must use the reduced Fortune, not the sheet value.",
    "status": "ACTIVE",
    "source": "https://hypixelskyblock.minecraft.wiki/w/Pests",
    "lastVerified": "2026-09-16"
  },
  {
    "id": "mantid-kill-credit-piece",
    "name": "One Mantid piece in the kill set keeps its stacks building",
    "effect": "Mantid's temporary stacks are earned from Pest kills. A late-game rotation swaps Mossy Helianthus for full Mantid Helianthus shortly before the Pest cooldown is ready, and the kill set keeps one Mantid armour piece so kill credit for those stacks continues.",
    "why": "The stacks are tied to kills, not to wearing the full set at the time of the kill, so a single retained piece preserves progress across a swap. Treating Mantid as all-or-nothing loses this.",
    "handling": "Model Mantid as a stacking buff with its own accrual condition, and allow a partial set in the kill loadout purely for credit.",
    "status": "ACTIVE",
    "source": "https://hypixelskyblock.minecraft.wiki/w/Tutorial:Farming_Guide",
    "lastVerified": "2026-09-16"
  },
  {
    "id": "contest-medals-gate-turbo-crop",
    "name": "Contest medals gate Turbo-Crop levels per crop",
    "effect": "A Bronze result in a crop lets Turbo-Crop IV work for that crop, and Silver lets Turbo-Crop V work. Turbo-Crop itself reaches VII, with VI from a Turbo Gourd and VII from an Enchanted Turbo Gourd.",
    "why": "The enchantment level a player owns is not the level that applies. Without the medal for that specific crop the higher levels do nothing, so a book purchase can be entirely wasted.",
    "handling": "Gate the effective Turbo-Crop level on the per-crop medal, and prompt for the medal before recommending IV or V.",
    "status": "ACTIVE",
    "source": "https://hypixelskyblock.minecraft.wiki/w/Tutorial:Farming_Guide",
    "lastVerified": "2026-09-16"
  },
  {
    "id": "gold-medals-raise-farming-cap",
    "name": "Each unique Gold crop raises the Farming level cap by one",
    "effect": "Every unique crop in which a Gold contest result is achieved lets Anita raise the Farming level cap by one, up to 10 upgrades and Farming 60.",
    "why": "Farming levels above 50 are not a grind, they are a contest unlock, and each one is worth +4 Farming Fortune. The prerequisite is breadth across crops, not depth in one.",
    "handling": "Treat the cap as a prerequisite chain on unique Gold crops and count the remaining Fortune it unlocks, not just the XP.",
    "status": "ACTIVE",
    "source": "https://hypixelskyblock.minecraft.wiki/w/Tutorial:Farming_Guide",
    "lastVerified": "2026-09-16"
  },
  {
    "id": "tool-tier-gate-levels",
    "name": "Mk. II and Mk. III unlock at tool level 15 and 30",
    "effect": "A Specialized Farming Tool gains XP from harvesting its matching mature crop. The Mk. II craft becomes available at tool level 15 and Mk. III at level 30; each raises the tool's rarity and lets it keep levelling. Overclocker 3000 is what carries levels 40 to 50.",
    "why": "Rarity is not cosmetic: it scales reforges and gemstone values, so the tier upgrade changes the value of everything already on the tool. The gates are also hard stops, so a level target above them is unreachable without the craft.",
    "handling": "Model tier as a prerequisite at levels 15 and 30 and as a multiplier on reforge and gemstone contributions, not as a flat Fortune bonus.",
    "status": "ACTIVE",
    "source": "https://hypixelskyblock.minecraft.wiki/w/Tutorial:Farming_Guide",
    "lastVerified": "2026-09-16"
  },
  {
    "id": "sprayonator-tiers",
    "name": "Sprayonator tiers multiply the spray, not just its duration",
    "effect": "The regular Sprayonator uses one material and lasts 30 minutes. The Juicy Sprayonator can use three materials for twice the base effect and lasts 45 minutes. The Salty Sprayonator can use five materials for triple the base effect and lasts 60 minutes. With Bonus Pest Chance material that is +25, +50 and +75 respectively.",
    "why": "The upgrade changes both magnitude and material cost, so its value depends on material price and on how much of the duration is actually farmed. Treating it as a longer buff alone understates it.",
    "handling": "Model the spray as effect x duration against recurring material cost, and count unused duration as waste.",
    "status": "ACTIVE",
    "source": "https://hypixelskyblock.minecraft.wiki/w/Tutorial:Farming_Guide",
    "lastVerified": "2026-09-16"
  },
  {
    "id": "brown-bandana-bestiary-scaling",
    "name": "Brown Bandana scales with Pest Bestiary, excluding two mobs",
    "effect": "The Brown Bandana grants +0.2 Bonus Pest Chance per eligible Pest Bestiary tier, up to 45. Timestalk Clone and Zombuddy tiers do not count toward it.",
    "why": "Its value is not fixed but tied to bestiary progress, and two of the mobs that do raise bestiary Fortune do not raise this. Reading it off the bestiary total would overstate it.",
    "handling": "Compute from eligible bestiary tiers only, and exclude Timestalk Clone and Zombuddy.",
    "status": "ACTIVE",
    "source": "https://hypixelskyblock.minecraft.wiki/w/Tutorial:Farming_Guide",
    "lastVerified": "2026-09-16"
  },
  {
    "id": "sunset-day-night-tradeoff",
    "name": "Sunset V trades daytime Overbloom against Visitor speed at night",
    "effect": "Sunset V gives 5 Overbloom during the day, but shortens the Visitor cooldown by 5% while breaking crops at night.",
    "why": "The two halves of the same enchantment pull toward opposite Island Time settings, so the right choice depends on whether Overbloom or Visitor throughput is worth more to that player.",
    "handling": "Never add both halves. Evaluate per frozen-time setting and compare against the Visitor value the player actually realises.",
    "status": "ACTIVE",
    "source": "https://hypixelskyblock.minecraft.wiki/w/Tutorial:Farming_Guide",
    "lastVerified": "2026-09-16"
  },
  {
    "id": "greenhouse-rebalances",
    "name": "Greenhouse mutation values are rebalanced repeatedly",
    "effect": "The Greenhouse has been rebalanced several times, including a mutation multiplier change in August 2026.",
    "why": "It is a direct warning for this app: a cached or hard-coded Greenhouse profit figure goes stale quickly and silently, which is exactly the failure the correctness rules exist to prevent.",
    "handling": "Never hard-code Greenhouse mutation values. Keep them dated, and treat any figure older than the last rebalance as unverified.",
    "status": "VERIFY",
    "source": "https://hypixelskyblock.minecraft.wiki/w/Tutorial:Farming_Guide",
    "lastVerified": "2026-09-16"
  },
  {
    "id": "mushroom-farming-xp",
    "name": "Mushroom gives the most Farming XP per block",
    "effect": "Mushroom unlocks at Garden IX and gives 6 base Farming XP per block, which makes it the crop of choice when the goal is Farming levels rather than coins.",
    "why": "The best crop for XP is not the best crop for profit, so a single ranking would give the wrong answer to one of the two goals.",
    "handling": "Rank crops separately for XP per hour and coins per hour, and say which goal a recommendation serves.",
    "status": "ACTIVE",
    "source": "https://hypixelskyblock.minecraft.wiki/w/Tutorial:Farming_Guide",
    "lastVerified": "2026-09-16"
  },
  {
    "id": "beth-quest-gates-crop-analyzer",
    "name": "Beth's quest spans several Garden visits and gates the Crop Analyzer",
    "effect": "Beth in the Desert Settlement must be served as a Visitor, and her quest takes several Garden visits. Its later part is required for the Crop Analyzer, which is not unlocked with the Greenhouse itself.",
    "why": "It is a wall-clock prerequisite, not a cost. Starting it late blocks Greenhouse progression while waiting for Visitor arrivals, which no amount of coins shortens.",
    "handling": "Model as a passive time-gated prerequisite and recommend starting it long before the Greenhouse is the active goal.",
    "status": "ACTIVE",
    "source": "https://hypixelskyblock.minecraft.wiki/w/Tutorial:Farming_Guide",
    "lastVerified": "2026-09-16"
  },
  {
    "id": "sundial-frees-boot-slot",
    "name": "A Sundial moves Speed control off the boots",
    "effect": "After reaching Sunflower VII, crafting a Sundial and giving it to Sam unlocks per-crop Speed settings at the Desk.",
    "why": "It frees the boot slot: without it, hitting the right farming Speed means wearing Rancher's Boots instead of the Farming Fortune boots, which is a direct Fortune loss.",
    "handling": "Once the Sundial is owned, stop treating Rancher's Boots as part of any farming setup and keep the Fortune boots equipped.",
    "status": "ACTIVE",
    "source": "https://hypixelskyblock.minecraft.wiki/w/Tutorial:Farming_Guide",
    "lastVerified": "2026-09-16"
  },
  {
    "id": "farming-attributes-are-not-all-farming-fortune",
    "name": "Only four of the twelve farming attributes give Farming Fortune",
    "effect": "Solar Power (Firefly, +5-50 by day), Lunar Power (Lunar Moth, +5-50 by night), Pest Fortune (Cricket, +5-50 on Pests) and Infiltration (Earthworm, +3-30 while the current plot has a Pest) grant Farming Fortune. Pest Luck, Bonus Pest Chance, Sprayonator Serendipity, Pest Cooldown, Enchanted Farmer, Visitor Bait, Fancy Visit and Garden Wisdom grant something else entirely.",
    "why": "Every one of these is levelled the same way, shown in the same Hunting Box and described in the same wiki table, which makes it easy to read the whole set as one Fortune pool and add up +5-50 twelve times.",
    "handling": "Each attribute is a separate scored entry carrying its own metric, so the planner can never sum them into Farming Fortune. Only the four Fortune attributes use the Crop Yield metric, and three of those four are conditional (day, night, Pest present) rather than always-on.",
    "status": "ACTIVE",
    "lastVerified": "2026-09-16",
    "source": "https://hypixelskyblock.minecraft.wiki/w/Attributes"
  },
  {
    "id": "pest-cooldown-has-no-published-per-level-value",
    "name": "Pest Cooldown (Moth Shard) publishes no per-level scaling",
    "effect": "The wiki states, as a flat figure on both the attribute list and the Moth Shard page, that the attribute reduces the spawn cooldown of Pest by 0.5s, while all eleven other farming attributes print an explicit level 1 to level 10 range.",
    "why": "Attributes level to 10, so a flat figure is either a genuinely unscaling effect or an undocumented range. Assuming 0.5s per level would silently invent a 5s reduction that no source states.",
    "handling": "Kept as a VERIFY entry with stepGain 0, so it appears in the shard list and can be filled in manually but never contributes a derived number. It becomes scored only when a per-level value is sourced.",
    "status": "VERIFY",
    "lastVerified": "2026-09-16",
    "source": "https://hypixelskyblock.minecraft.wiki/w/Moth_Shard"
  }
];

export const COMING_SOON = [
  {
    "id": "greenhouse-watering-decay",
    "name": "Greenhouse watering/decay",
    "status": "Announced 1 Sep 2026",
    "effect": "Watering and decay planned to freeze plants instead of killing them.",
    "treatment": "0 weight",
    "source": "https://hypixel.net/threads/hypixel-skyblock-0-27-1-chocolate-factory-improvements-qol-changes-and-more.6147732/page-2",
    "notes": "No release date."
  },
  {
    "id": "mutation-spreading-minimum",
    "name": "Mutation spreading minimum",
    "status": "Announced 1 Sep 2026",
    "effect": "Guaranteed minimum amount of mutation spreading before crops decay.",
    "treatment": "0 weight",
    "source": "https://hypixel.net/threads/hypixel-skyblock-0-27-1-chocolate-factory-improvements-qol-changes-and-more.6147732/page-2",
    "notes": "Details not final."
  },
  {
    "id": "unique-crop-bonus-rework",
    "name": "Unique Crop Bonus rework",
    "status": "Announced 1 Sep 2026",
    "effect": "New Attribute Shard intended to cover the Unique Crop Bonus; bonus planned to drop from 12 to 10.",
    "treatment": "0 weight",
    "source": "https://hypixel.net/threads/hypixel-skyblock-0-27-1-chocolate-factory-improvements-qol-changes-and-more.6147732/page-2",
    "notes": "Do not pre-value the shard until released."
  }
];
