/**
 * Beginner-facing explanations for Farming420.
 *
 * These records are intentionally separate from profile/account state. Each
 * mechanic has a stable anchor so global search can route directly to the
 * explanation instead of sending players to an unrelated settings control.
 *
 * Current mechanics were rechecked on 2026-09-27 against the maintained
 * Hypixel SkyBlock community wiki and the repository research layer. The
 * Farming Fortune index currently warns that some post-Greenhouse details are
 * stale, so entries sourced from it only repeat narrow facts that are also
 * represented by Farming420's current data/research.
 */

const VERIFIED_CURRENT = '2026-09-27';
const VERIFIED_RESEARCH = '2026-09-16';

const SOURCE = Object.freeze({
  garden: 'https://hypixelskyblock.minecraft.wiki/w/The_Garden',
  farmingFortune: 'https://hypixelskyblock.minecraft.wiki/w/Farming_Fortune',
  overbloom: 'https://hypixelskyblock.minecraft.wiki/w/Overbloom',
  bonusPestChance: 'https://hypixelskyblock.minecraft.wiki/w/Bonus_Pest_Chance',
  pests: 'https://hypixelskyblock.minecraft.wiki/w/Pests',
  vacuums: 'https://hypixelskyblock.minecraft.wiki/w/Vacuums',
  recombobulator: 'https://hypixelskyblock.minecraft.wiki/w/Recombobulator_3000',
  gemstoneSlot: 'https://hypixelskyblock.minecraft.wiki/w/Gemstone_Slot',
  reforging: 'https://hypixelskyblock.minecraft.wiki/w/Reforging',
  enchantments: 'https://hypixelskyblock.minecraft.wiki/w/Enchantments',
  rarity: 'https://hypixelskyblock.minecraft.wiki/w/Rarity',
  farmingGuide: 'https://hypixelskyblock.minecraft.wiki/w/Tutorial:Farming_Guide',
  jacob: 'https://hypixelskyblock.minecraft.wiki/w/Jacob%27s_Farming_Contest',
  greenhousePatch: 'https://hypixel.net/threads/hypixel-skyblock-0-24-the-greenhouse.6027542/page-3',
});

function freezeEntry(entry) {
  return Object.freeze({
    ...entry,
    keywords: Object.freeze([...(entry.keywords || [])]),
  });
}

export const INFO_SECTIONS = Object.freeze([
  Object.freeze({
    id: 'mechanics',
    eyebrow: 'Core mechanics',
    title: 'Know which stat does which job',
    description: 'FF, Crop Fortune, Overbloom and BPC are separate axes. Keeping them separate prevents the most common early-game planning mistakes.',
  }),
  Object.freeze({
    id: 'items',
    eyebrow: 'Item upgrades',
    title: 'Understand upgrades before buying them',
    description: 'Rarity, reforges, enchantments and gemstone slots belong to the physical item. A generic upgrade is only useful when the item and the active job can use it.',
  }),
  Object.freeze({
    id: 'pests',
    eyebrow: 'Pest system',
    title: 'Spawn, kill and loot are different phases',
    description: 'Pest spawning, Vacuum handling, guaranteed drops and rare drops use different stats. The detailed spawn/loot pipelines are shown below these reference cards.',
  }),
  Object.freeze({
    id: 'places',
    eyebrow: 'Important places',
    title: 'Where the system actually lives',
    description: 'Use these entries when a guide tells you to unlock, buy or configure something and you do not know where to go.',
  }),
  Object.freeze({
    id: 'crops',
    eyebrow: 'Crop-specific strategy',
    title: 'Keep every crop-specific upgrade on its own crop',
    description: 'Each crop has its own progression and specialized tool. Exact farm geometry, speed and angles are not guessed while the research layer still marks them as crop-by-crop gaps.',
  }),
]);

export const INFO_ENTRIES = Object.freeze([
  freezeEntry({
    id: 'farming-mechanics',
    anchor: 'info-farming-mechanics',
    section: 'mechanics',
    label: 'Mental model',
    title: 'How Farming420 separates farming mechanics',
    what: 'Farming420 keeps account progression, crop-specific progression, physical-item upgrades, mutually exclusive loadouts, temporary effects and Pest phases as separate layers.',
    why: 'Two bonuses that exist in the game are not automatically active at the same time. Separating the layers prevents double-counting a second held tool, another crop\'s Fortune or a Pest-only effect.',
    when: 'Use this model from the first Garden setup onward, especially before comparing upgrades that affect different phases.',
    where: 'Account and crop progression live in Garden/Effects; physical items live in Tools and Loadouts; explanations stay here in Info.',
    source: SOURCE.garden,
    lastVerified: VERIFIED_CURRENT,
    keywords: ['farming mechanics', 'how farming works', 'layers', 'double count', 'beginner'],
  }),
  freezeEntry({
    id: 'farming-fortune',
    anchor: 'info-farming-fortune',
    section: 'mechanics',
    label: 'FF',
    title: 'Farming Fortune',
    what: 'Farming Fortune is the general farming drop stat. It increases relevant crop output and applies to the guaranteed crop-style part of Pest drops, but it is not the current rare-Pest-drop stat.',
    why: 'FF is one of the main normal-yield stats, so permanent FF and active-setup FF matter across many farming goals.',
    when: 'Relevant as soon as you farm for collection, coins or contest score. Do not use it as a replacement for Overbloom when evaluating rare crops.',
    where: 'Read the stat in your SkyBlock stat breakdown and let Farming420 sync item/setup contributions where possible.',
    source: SOURCE.farmingFortune,
    sourceNote: 'The maintained Farming Fortune index flags some post-Greenhouse details as outdated; this entry only uses its stable stat scope together with the current Pest/Overbloom sources.',
    lastVerified: VERIFIED_CURRENT,
    keywords: ['ff', 'farming fortune', 'fortune', 'normal drops', 'yield'],
  }),
  freezeEntry({
    id: 'crop-fortune',
    anchor: 'info-crop-fortune',
    section: 'mechanics',
    label: 'Crop stat',
    title: 'Crop Fortune',
    what: 'Crop Fortune is scoped to one matching crop. Melon Crop Fortune helps Melon; it does not become account-wide Farming Fortune and it does not help Wheat.',
    why: 'Adding every crop\'s Fortune together makes profit and upgrade comparisons wrong. Farming420 keeps each crop in its own bucket.',
    when: 'Relevant as soon as you choose a main crop, buy Crop Upgrades, level a specialized tool or compare crop-specific upgrades.',
    where: 'Crop Upgrades and crop progression are managed from The Garden/Desk. Select the crop in Farming420 Garden to see its own state.',
    source: SOURCE.garden,
    lastVerified: VERIFIED_CURRENT,
    keywords: ['crop fortune', 'cf', 'crop upgrade', 'desk', 'matching crop'],
  }),
  freezeEntry({
    id: 'overbloom',
    anchor: 'info-overbloom',
    section: 'mechanics',
    label: 'Rare drops',
    title: 'Overbloom',
    what: 'Overbloom increases the chance of eligible Rare Crops. The current formula multiplies the base chance by 1 + Overbloom/100. Since the May 2026 Pest change, current non-guaranteed Pest rare drops use Overbloom instead of Farming Fortune.',
    why: 'A build with more FF is not automatically better for rare-drop farming. Overbloom has its own value and must be evaluated against the rare drops and roll rate of the current activity.',
    when: 'Mostly relevant once Rare Crops, Pest RNG, Feast-related farming or dedicated rare-drop setups matter to you.',
    where: 'Overbloom comes from specific tools, reforges, enchants, pets, pet items, accessories and conditional effects. Check the active physical setup rather than entering one generic permanent value.',
    source: SOURCE.overbloom,
    lastVerified: VERIFIED_CURRENT,
    keywords: ['overbloom', 'rare crop', 'rare drops', 'rng', 'pest rng'],
  }),
  freezeEntry({
    id: 'bonus-pest-chance',
    anchor: 'info-bonus-pest-chance',
    section: 'mechanics',
    label: 'BPC',
    title: 'Bonus Pest Chance',
    what: 'Bonus Pest Chance controls how many Pests can spawn at once. Every full 100 BPC guarantees one additional Pest and the remainder is the percent chance for one more.',
    why: 'BPC is a spawn-side stat, not loot quality. Full 100-point steps also let one more active Pest remain before the Garden starts applying its Farming/Crop Fortune penalty.',
    when: 'Relevant when you deliberately farm Pests or when normal farming produces enough Pests that spawn size and Pest pressure affect your rotation.',
    where: 'BPC can come from Pest-specific armor, equipment, pets, pet items, enchants, reforges, chips, consumables and attributes. Configure those real sources in their own Farming420 tabs.',
    source: SOURCE.bonusPestChance,
    lastVerified: VERIFIED_CURRENT,
    keywords: ['bpc', 'bonus pest chance', 'pest chance', 'spawn pests', '100 bpc'],
  }),
  freezeEntry({
    id: 'pest-grade',
    anchor: 'info-pest-grade',
    section: 'mechanics',
    label: 'Pest pressure',
    title: 'Pest Grade / active Pest pressure',
    what: '"Pest Grade" is treated here as a beginner-facing explanation for active Pest pressure, not as a separate editable SkyBlock account stat. The real inputs are active Pest count, BPC and the resulting Fortune penalty.',
    why: 'With less than 100 BPC, the Fortune penalty starts at 4 active Pests. Each full 100 BPC moves that starting point one Pest later.',
    when: 'Relevant from Garden V onward whenever Pests are left alive while you continue normal farming.',
    where: 'Watch the active Pests in The Garden and clear them with a Vacuum when they interfere with your farming plan. There is no separate Pest Grade field to enter in Farming420.',
    source: SOURCE.pests,
    lastVerified: VERIFIED_CURRENT,
    keywords: ['pest grade', 'pest pressure', 'active pests', 'fortune penalty', 'pest penalty'],
  }),
  freezeEntry({
    id: 'recombobulator',
    anchor: 'info-upgrade-recombobulator',
    section: 'items',
    label: 'Rarity upgrade',
    title: 'Recombobulator 3000',
    what: 'A Recombobulator 3000 raises the rarity of most eligible items by one tier. It does not add a universal flat Farming Fortune value by itself.',
    why: 'Higher effective rarity can increase rarity-scaled reforge and gemstone stats, so the real gain depends on the exact item and everything already attached to it.',
    when: 'Usually a later upgrade after the item, its important enchants/reforge and useful gemstone slots are already worth investing in.',
    where: 'It is a tradeable Bazaar item and also comes from Catacombs boss-collection rewards and Dungeon Reward Chests. Apply it only to an eligible physical item.',
    source: SOURCE.recombobulator,
    lastVerified: VERIFIED_CURRENT,
    keywords: ['recomb', 'recombobulator', 'rarity upgrade', 'mythic rarity'],
  }),
  freezeEntry({
    id: 'gemstones',
    anchor: 'info-upgrade-gemstones',
    section: 'items',
    label: 'Item sockets',
    title: 'Gemstones',
    what: 'Gemstones only work in gemstone slots that the concrete item actually has. Peridot is the Farming Fortune gemstone type.',
    why: 'The gemstone contribution depends on slot compatibility, gemstone quality and host-item rarity. Assuming every item has every slot overstates a setup.',
    when: 'Relevant after you own a compatible farming item and the cost of improving its real slots makes sense for that stage of progression.',
    where: 'Inspect the item\'s actual gemstone slots first. Farming420 exposes only supported slots and keeps locked/unavailable sockets separate from an inserted gemstone.',
    source: SOURCE.gemstoneSlot,
    lastVerified: VERIFIED_CURRENT,
    keywords: ['gem', 'gems', 'gemstone', 'gemstones', 'peridot', 'socket', 'slots'],
  }),
  freezeEntry({
    id: 'reforges',
    anchor: 'info-upgrade-reforges',
    section: 'items',
    label: 'Item modifier',
    title: 'Reforges',
    what: 'A reforge is an item modifier. Reforge stats can scale with item rarity, and the stat only matters while the relevant item is actually worn or held.',
    why: 'Farming, Pest spawning, Pest killing and rare-drop setups can want different reforges. Comparing only the reforge name without the active phase can produce the wrong upgrade.',
    when: 'Relevant once you have an item worth keeping long enough to optimize and before paying for a more expensive reforge stone.',
    where: 'Basic reforging is available through the Blacksmith/The Hex. Reforge Stones can be applied with an Anvil or The Hex when the item is compatible.',
    source: SOURCE.reforging,
    lastVerified: VERIFIED_CURRENT,
    keywords: ['reforge', 'reforges', 'modifier', 'blacksmith', 'hex', 'reforge stone'],
  }),
  freezeEntry({
    id: 'enchantments',
    anchor: 'info-upgrade-enchantments',
    section: 'items',
    label: 'Item upgrade',
    title: 'Enchantments',
    what: 'Enchantments are item-compatible upgrades with their own levels and conditions. Farming enchants can add direct Fortune, crop-specific Fortune or conditional Pest/Overbloom effects.',
    why: 'Treating every enchant as generic stats loses its crop, item and activation conditions. Farming420 tracks the exact enchant and level on the physical item.',
    when: 'Relevant throughout progression, but higher/endcap levels should be compared against cheaper missing upgrades before buying them.',
    where: 'Use the Enchantment Table, Anvil or the item-specific acquisition route for the enchant. Farming420 shows only enchantments compatible with the selected item where support is verified.',
    source: SOURCE.enchantments,
    lastVerified: VERIFIED_CURRENT,
    keywords: ['enchant', 'enchants', 'enchantment', 'enchantments', 'books'],
  }),
  freezeEntry({
    id: 'rarity',
    anchor: 'info-upgrade-rarity',
    section: 'items',
    label: 'Item capability',
    title: 'Rarity and item capabilities',
    what: 'Rarity is part of the physical item state. It can change the strength and cost of reforges and the stat value of gemstones, but the item itself still decides which systems it supports.',
    why: 'A higher rarity does not create a gemstone slot or reforge compatibility that the item never had. Farming420 therefore models capability and rarity separately.',
    when: 'Relevant when comparing a Recombobulator, rarity-scaled reforge or gemstone upgrade.',
    where: 'Read the item rarity from its tooltip. Farming420 keeps base item identity and effective rarity together on the item editor.',
    source: SOURCE.rarity,
    lastVerified: VERIFIED_CURRENT,
    keywords: ['rarity', 'item capability', 'capabilities', 'effective rarity', 'mythic'],
  }),
  freezeEntry({
    id: 'item-acquisition',
    anchor: 'info-item-acquisition',
    section: 'items',
    label: 'Where to get things',
    title: 'Finding and obtaining farming items',
    what: 'Farming items use different acquisition routes: Garden shops/progression, mob or Pest drops, crafting, Bazaar, Dungeon rewards and other item-specific sources.',
    why: 'Guessing one generic "in-game location" creates bad instructions and bad cost assumptions, especially for Ironman or progression-gated items.',
    when: 'Use this whenever Farming420 names an item you do not own or you need to understand why its upgrade is unavailable.',
    where: 'Open the source link on the relevant Info or upgrade entry and follow the current item-specific route. Unknown acquisition details stay explicit instead of being replaced by a fake placeholder.',
    source: SOURCE.farmingGuide,
    lastVerified: VERIFIED_RESEARCH,
    keywords: ['where to get', 'where is', 'obtain', 'obtaining', 'location', 'find item', 'acquisition'],
  }),
  freezeEntry({
    id: 'pest-spawning',
    anchor: 'info-pest-spawning',
    section: 'pests',
    label: 'Spawn phase',
    title: 'How Pest spawning works',
    what: 'Pests can spawn while actively farming on The Garden once the Pest system is unlocked. A spawn only happens while the system is eligible/off cooldown; BPC changes the number spawned at once, not the rare-drop quality.',
    why: 'Spawn-rate/cooldown gear is only valuable during the spawn phase. Wearing it for the entire farming rotation can sacrifice normal crop output for no reason.',
    when: 'Relevant from Garden V, and especially once you intentionally build a BPC setup instead of treating Pests as occasional interruptions.',
    where: 'Farm eligible Garden plots, then use the BPC set shortly before the effective Pest cooldown is ready. Sprayonator/Vinyl effects choose or weight Pest types; they are separate from loot stats.',
    source: SOURCE.pests,
    lastVerified: VERIFIED_CURRENT,
    keywords: ['pest spawning', 'spawn pests', 'pest cooldown', 'sprayonator', 'vinyl', 'spawn phase'],
  }),
  freezeEntry({
    id: 'pest-loot',
    anchor: 'info-pest-loot',
    section: 'pests',
    label: 'Loot phase',
    title: 'Guaranteed Pest drops vs rare Pest drops',
    what: 'Guaranteed crop-style Pest drops and non-guaranteed rare Pest drops are separate. Current guaranteed crop drops use applicable Farming/Crop Fortune; current rare Pest drops use Overbloom.',
    why: 'Putting Pest Farming Fortune into the rare-drop formula is a stale pre-May-2026 model and overvalues the wrong upgrades.',
    when: 'Relevant whenever you compare Beady/Buzzing, Bug Blender, Pest-only Fortune, Overbloom or a dedicated Pest-killing loadout.',
    where: 'Use the Pests analysis for the active Pest and the Info pipeline below. Keep spawn, kill, guaranteed-drop and rare-roll stats in their own stages.',
    source: SOURCE.pests,
    lastVerified: VERIFIED_CURRENT,
    keywords: ['pest loot', 'pest drops', 'rare pest drop', 'guaranteed pest drop', 'pest fortune'],
  }),
  freezeEntry({
    id: 'vacuum',
    anchor: 'info-vacuum',
    section: 'pests',
    label: 'Pest tool',
    title: 'Vacuum',
    what: 'A Vacuum is the held Pest tool. It pulls/damages Pests and is the tool used to kill them; its held-item stats belong to the Pest phase, not normal crop harvesting.',
    why: 'Vacuum damage is threshold-based: extra damage matters when it reduces the number of hits/cycles needed. Vacuum Farming Fortune does not become normal crop-tool Fortune.',
    when: 'Relevant from Garden V as soon as Pests unlock. Upgrade it further when damage/range or Pest-phase stats save meaningful clear time or improve applicable Pest drops.',
    where: 'The first/current Vacuum progression is sold through SkyMart in The Garden and upgrades through the SkyMart Vacuum chain to InfiniVacuum variants.',
    source: SOURCE.vacuums,
    lastVerified: VERIFIED_CURRENT,
    keywords: ['vacuum', 'pest vacuum', 'skymart vacuum', 'hooverius', 'pest damage', 'pest tool'],
  }),
  freezeEntry({
    id: 'farm-merchant',
    anchor: 'info-place-farm-merchant',
    section: 'places',
    label: 'Hub starter shop',
    title: 'Farm Merchant',
    what: 'The Farm Merchant is the simple starter route for a Rookie Hoe before Garden progression and specialized farming tools take over.',
    why: 'It gives a new profile a cheap first farming tool without implying that the Rookie Hoe remains the correct tool after crop-specific progression unlocks.',
    when: 'Relevant at the very start of Farming, before your Garden and specialized crop tools become the main progression path.',
    where: 'Find the Farm Merchant in the Hub farming area. The current farming guide lists the Rookie Hoe as the first hoe to buy there.',
    source: SOURCE.farmingGuide,
    lastVerified: VERIFIED_CURRENT,
    keywords: ['farm merchant', 'rookie hoe', 'starter hoe', 'hub farming', 'first farming tool'],
  }),
  freezeEntry({
    id: 'beth',
    anchor: 'info-place-beth',
    section: 'places',
    label: 'Greenhouse quest',
    title: 'Beth',
    what: 'Beth is part of the Greenhouse progression questline that leads to access to the Crop Analyzer.',
    why: 'The Crop Analyzer is progression content, not a profile setting. If it is unavailable, the relevant problem is quest progression rather than a missing Farming420 value.',
    when: 'Relevant once Greenhouse mutation progression and the Crop Analyzer become part of your farming goals.',
    where: 'Continue Beth\'s quest/visitor progression and follow the Underground Lab sequence with Jake. Hypixel\'s Greenhouse release notes tie Crop Analyzer access to completing the new part of Beth\'s questline.',
    source: SOURCE.greenhousePatch,
    lastVerified: VERIFIED_CURRENT,
    keywords: ['beth', 'crop analyzer', 'greenhouse', 'underground lab', 'jake', 'beth quest'],
  }),
  freezeEntry({
    id: 'garden',
    anchor: 'info-place-garden',
    section: 'places',
    label: 'Main farming island',
    title: 'The Garden',
    what: 'The Garden is the main farming island/system: plots, crops, visitors, Pest progression, Crop Upgrades and Garden progression are centered here.',
    why: 'Many farming stats and progression systems are Garden-specific. Farming on the Private Island does not reproduce the full Garden rules.',
    when: 'Unlock it at SkyBlock Level 5 and use it as the default place for Farming420 progression.',
    where: 'Reach SkyBlock Level 5, then use Sam/the Garden unlock flow. After the first visit, Garden progression menus are available in the game.',
    source: SOURCE.garden,
    lastVerified: VERIFIED_CURRENT,
    keywords: ['garden', 'the garden', 'sam', 'unlock garden', 'skyblock level 5'],
  }),
  freezeEntry({
    id: 'garden-desk',
    anchor: 'info-place-garden-desk',
    section: 'places',
    label: 'Garden hub',
    title: 'Garden Desk',
    what: 'The Desk is the central Garden configuration/progression interface for plots and crop-related Garden systems.',
    why: 'If an upgrade is crop-specific account progression rather than a physical item, the Desk/Garden progression is usually the first place to check.',
    when: 'Use it from early Garden progression onward for crop and plot management.',
    where: 'Open the Desk while on The Garden; the repository research also tracks /desk as the direct Garden command.',
    source: SOURCE.garden,
    lastVerified: VERIFIED_CURRENT,
    keywords: ['desk', 'garden desk', '/desk', 'crop upgrades', 'plots'],
  }),
  freezeEntry({
    id: 'skymart',
    anchor: 'info-place-skymart',
    section: 'places',
    label: 'Garden shop',
    title: 'SkyMart',
    what: 'SkyMart is the Garden shop used for important farming tools and utility/progression items, including the Vacuum progression.',
    why: 'Copper is a progression currency, so buying every available item is not the same as buying the next useful upgrade for your active crop or Pest plan.',
    when: 'Relevant immediately after entering Garden progression and whenever an item source says it costs Copper.',
    where: 'Find SkyMart in The Garden or access the corresponding Garden shop flow. Check the item source before spending Copper.',
    source: SOURCE.garden,
    lastVerified: VERIFIED_CURRENT,
    keywords: ['skymart', 'copper', 'garden shop', 'vacuum shop', 'farming tools'],
  }),
  freezeEntry({
    id: 'pesthunter-phillip',
    anchor: 'info-place-pesthunter-phillip',
    section: 'places',
    label: 'Pest progression',
    title: 'Pesthunter Phillip',
    what: 'Pesthunter Phillip is the Pest progression/shop NPC. Pest currency can be exchanged for a temporary Farming Fortune effect and Pest-related progression/items.',
    why: 'Pest currency has competing uses, so spending it for a temporary buff is a choice rather than permanent free Fortune.',
    when: 'Relevant once you are clearing Pests regularly and especially before longer Pest-farming sessions.',
    where: 'Find Pesthunter Phillip in The Garden. Use the current Pests/Pesthunter source for the live exchange cap instead of relying on an old guide.',
    source: SOURCE.pests,
    lastVerified: VERIFIED_CURRENT,
    keywords: ['pesthunter phillip', 'phillip', 'pest currency', 'temporary farming fortune', 'pest shop'],
  }),
  freezeEntry({
    id: 'jacob-anita',
    anchor: 'info-place-jacob-anita',
    section: 'places',
    label: 'Contest progression',
    title: 'Jacob and Anita',
    what: 'Jacob\'s Farming Contests and Anita upgrades are a separate progression route tied to crop contests, medals/tickets and Farming progression rewards.',
    why: 'Contest progression can unlock or gate farming upgrades, but a contest result is not an always-active account stat by itself.',
    when: 'Jacob\'s Farming Contests become relevant from Farming 10 onward.',
    where: 'Use the Jacob/Anita contest progression in The Garden and the current contest source for live brackets and requirements.',
    source: SOURCE.jacob,
    lastVerified: VERIFIED_RESEARCH,
    keywords: ['jacob', 'anita', 'farming contest', 'medal', 'jacob ticket', 'farming 10'],
  }),
  freezeEntry({
    id: 'blacksmith-hex',
    anchor: 'info-place-blacksmith-hex',
    section: 'places',
    label: 'Item modification',
    title: 'Blacksmith, Anvil and The Hex',
    what: 'These are item-modification routes used for reforges and other physical-item upgrades rather than account progression.',
    why: 'A reforge belongs to the item you apply it to, so the Farming420 item editor should match the real physical item instead of a global setting.',
    when: 'Relevant when applying or replacing a reforge or another supported item-level modifier.',
    where: 'Use the Blacksmith/The Hex for reforging; Reforge Stones can be applied through an Anvil or The Hex when compatible.',
    source: SOURCE.reforging,
    lastVerified: VERIFIED_CURRENT,
    keywords: ['blacksmith', 'hex', 'anvil', 'reforge stone', 'apply reforge'],
  }),
]);

export function cropStrategyInfo(crops = []) {
  return crops.map(crop => freezeEntry({
    id: `crop-${crop.id}`,
    anchor: `info-crop-${crop.id}`,
    section: 'crops',
    label: `${crop.name} strategy`,
    title: crop.name,
    what: `${crop.name} has its own crop-specific progression and uses ${crop.tool} as its specialized physical tool in Farming420.`,
    why: `Only bonuses scoped to ${crop.name} should be counted as ${crop.name} Crop Fortune. Another crop's Crop Upgrade, Turbo enchant or specialized-tool progression must stay separate.`,
    when: `Relevant as soon as ${crop.name} is your main crop, a contest target or the crop whose profit/progression you are comparing.`,
    where: `Use Garden/Desk for ${crop.name} progression and Tools for the physical ${crop.tool}. Exact farm geometry, speed and angles are intentionally not guessed until current crop-specific research verifies them.`,
    source: crop.toolSource || SOURCE.farmingGuide,
    lastVerified: crop.toolVerified || VERIFIED_RESEARCH,
    keywords: [crop.id, crop.name, crop.tool, `${crop.name} strategy`, `${crop.name} tool`, `${crop.name} crop fortune`],
  }));
}

export function allInfoEntries(crops = []) {
  return [...INFO_ENTRIES, ...cropStrategyInfo(crops)];
}
